/* Generated By:JavaCC: Do not edit this line. TemplateParserConstants.java */
package org.yamcs.templating;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TemplateParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPEN_TAG = 2;
  /** RegularExpression Id. */
  int CLOSE_TAG = 3;
  /** RegularExpression Id. */
  int ELIF = 4;
  /** RegularExpression Id. */
  int ENDIF = 5;
  /** RegularExpression Id. */
  int ELSE = 6;
  /** RegularExpression Id. */
  int OPEN_VAR = 7;
  /** RegularExpression Id. */
  int OPEN_IF_TAG = 8;
  /** RegularExpression Id. */
  int OPEN_ELIF_TAG = 9;
  /** RegularExpression Id. */
  int TEXT = 10;
  /** RegularExpression Id. */
  int VAR = 13;
  /** RegularExpression Id. */
  int PIPE = 15;
  /** RegularExpression Id. */
  int CLOSE_VAR = 16;
  /** RegularExpression Id. */
  int CLOSE_IF_ELIF_TAG = 17;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;
  /** Lexical state. */
  int IN_VAR = 2;
  /** Lexical state. */
  int IN_CONDITION = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"{% comment %}\"",
    "<OPEN_TAG>",
    "<CLOSE_TAG>",
    "\"elif\"",
    "\"endif\"",
    "\"else\"",
    "<OPEN_VAR>",
    "\"{% if \"",
    "\"{% elif \"",
    "<TEXT>",
    "\"{% endcomment %}\"",
    "<token of kind 12>",
    "<VAR>",
    "\" \"",
    "\"|\"",
    "\"}}\"",
    "<CLOSE_IF_ELIF_TAG>",
  };

}
