package org.yamcs;

import org.yamcs.utils.TimeEncoding;

/**
 * Packet with acquisition time, generation time and sequence count.
 * <p>
 * It is assumed that (generation time, sequence count) uniquely identifies the packet
 * 
 * @author nm
 *
 */
public class TmPacket {
    private long rectime = TimeEncoding.INVALID_INSTANT; // Yamcs reception time
    private long gentime = TimeEncoding.INVALID_INSTANT; // generation time
    private long ertime = TimeEncoding.INVALID_INSTANT; // earth reception time

    private int seqCount;
    private byte[] pkt;
    boolean corrupted = false;

    public TmPacket(long rectime, byte[] pkt) {
        this.rectime = rectime;
        this.pkt = pkt;
    }

    public TmPacket(long rectime, long gentime, int seqCount, byte[] pkt) {
        this.rectime = rectime;
        this.gentime = gentime;
        this.seqCount = seqCount;
        this.pkt = pkt;
    }

    /**
     * The time when the packet has been generated by the payload.
     * 
     * @return
     */
    public long getGenerationTime() {
        return gentime;
    }

    public void setGenerationTime(long time) {
        this.gentime = time;
    }

    /**
     * Return the time when the packet has been received in Yamcs.
     * 
     * @return
     */
    public long getReceptionTime() {
        return rectime;
    }

    /**
     * The sequence count together with the generation time are supposed to uniquely identify the packet.
     * <p>
     * Note that for CCSDS space packets (as per CCSDS 133.0-B), this sequence count is a combination of the application
     * identifier(APID) and packet sequence count.
     * <p>
     * This means that the sequence count cannot be directly used to asses packet loss or packet ordering without having
     * more information about the nature of the count.
     * 
     * @return
     */
    public int getSeqCount() {
        return seqCount;
    }

    public void setSequenceCount(int seqCount) {
        this.seqCount = seqCount;
    }

    public byte[] getPacket() {
        return pkt;
    }

    public void setCorrupted(boolean corrupted) {
        this.corrupted = corrupted;
    }

    public boolean isCorrupted() {
        return corrupted;
    }

    /**
     * Returns the time when the packet has been received on earth or {@link TimeEncoding#INVALID_INSTANT} if it has not
     * been set.
     * <p>
     * The exact time returned will depend on how the packet has been received. For SLE links it will be the time when
     * the first bit of the last containing frame has been received at the ground station.
     * <p>
     * Some links will not set this parameter.
     * 
     * @return the time of the reception of the packet on ground.
     */
    public long getEarthReceptionTime() {
        return ertime;
    }

    public void setEarthRceptionTime(long ertime) {
        this.ertime = ertime;
    }

}
