language: java
jdk:
  - openjdk7

before_script:
# rocksdb copied from their travis.yml:
# use the yamcs clone that has make -j2 instead of -j32
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -y -qq gcc-4.9 g++-4.9 zlib1g-dev libbz2-dev libsnappy-dev libjemalloc-dev
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
 - wget https://gflags.googlecode.com/files/libgflags0_2.0-1_amd64.deb
 - sudo dpkg -i libgflags0_2.0-1_amd64.deb
 - wget https://gflags.googlecode.com/files/libgflags-dev_2.0-1_amd64.deb
 - sudo dpkg -i libgflags-dev_2.0-1_amd64.deb
 - git clone --depth 1 https://github.com/xpromache/rocksdb.git 
 - cd rocksdb && OPT=-DTRAVIS V=1 make rocksdbjava && sudo make install && sudo cp ./java/target/librocksdbjni-linux64.so /usr/local/lib/ && cd ..
#tokyocabinets
 - sudo apt-get install libtokyocabinet-dev
 - wget http://fallabs.com/tokyocabinet/javapkg/tokyocabinet-java-1.24.tar.gz
 - tar xzvf tokyocabinet-java-1.24.tar.gz
 - cd tokyocabinet-java-1.24 && ./configure && make && sudo make install && cd ..

script: mvn -Dsurefire.useFile=false test


