#!/bin/bash
### BEGIN INIT INFO
# Provides:          yamcs-server
# Required-Start:    $network $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Description:       Start the yamcs server
### END INIT INFO
#
YAMCS_USER=yamcs
YAMCS_HOME=/opt/yamcs
YAMCS_BIN=$YAMCS_HOME/bin/yamcs-server.sh
PID_FILE=/var/run/yamcs-server.pid
OUTERR=$YAMCS_HOME/log/yamcs-server.out # standard out and err go here


test -x $YAMCS_BIN || { echo "$YAMCS_BIN not installed";
        if [ "$1" = "stop" ]; then exit 0;
        else exit 5; fi; }

function is_running {
    pid=$1
    return $((1-`ps ww -p $pid -o args= | grep -c "yamcs-server.sh\|java.*yamcs.YamcsServer"`))
}

WAIT_FOR_START=120

case "$1" in
    start)
        echo -n "Starting the yamcs server...   "
        #set a high open file limit to avoid problems with rocksdb opening too many files
        ulimit -n 10000
        alreadyrunning=0
        if [ -s $PID_FILE ] ; then
            pid=`cat $PID_FILE`
            if is_running $pid ; then
                alreadyrunning=1
                echo "already running (pid=$pid)"
            else
                rm $PID_FILE
            fi
        fi

        if [ $alreadyrunning -eq 0 ] ; then
            touch $PID_FILE
            chown $YAMCS_USER $PID_FILE
            for i in 4 3 2 1 0; do
               if [ -f $OUTERR.$i ] ; then mv $OUTERR.$i $OUTERR.$((i+1)) ; fi
            done
            #written such that /etc/profile.d scripts do not trigger
            su -c "YAMCS_DAEMON=1; export YAMCS_DAEMON; cd; nohup $YAMCS_BIN >$OUTERR.0  2>&1 & echo \$! >$PID_FILE" $YAMCS_USER
            pid=`cat $PID_FILE`
            i=0
            #wait up to $WAIT_FOR_START seconds, maybe the database has to be loaded
            while [ $i -lt $WAIT_FOR_START ] ; do
                sleep 1
                if is_running $pid ; then
                    yamcsstartup=`grep yamcsstartup $OUTERR.0`
                    if [ "$yamcsstartup" != "" ] ; then
                        stat=`echo $yamcsstartup | cut -d " " -f 2`
                        if [ $stat = "success" ] ; then
                            echo done
                        else
                            echo $yamcsstartup | cut -d " " -f 3-
                            echo failure
                        fi
                        break
                    fi
                    i=$((i+1))
                else
                    echo "yamcs failed to start; see $OUTERR.0 for details"
                    exit 1
                fi
            done
            if [ $i -eq $WAIT_FOR_START ] ; then 
                echo "yamcs-server didn't finish the initialization in $WAIT_FOR_START seconds"
            fi
        fi

        ;;
    stop)
        echo -n "Shutting down the yamcs server...  "
        if [ -s $PID_FILE ] ; then
            pid=`cat $PID_FILE`
            i=0
            if is_running $pid ; then
                #first get a stack trace
                kill -3 $pid
                kill -TERM $pid
                while [ $i -lt 5 ] ; do
                    if is_running $pid ; then
                        kill -TERM $pid
                    else
                        rm $PID_FILE
                        break
                    fi
                    sleep 1
                    i=$((i+1))
                done

                if [ $i -eq 5 ] ; then 
                    echo timeout
                fi
            else
                echo -n "not running"
            fi
        else
            echo "not running ($PID_FILE doesn't exist)"
        fi
        ;;
    restart)
        ## Stop the service and regardless of whether it was
        ## running or not, start it again.
        $0 stop
        $0 start

        # Remember status and be quiet
        ;;
    status)
        echo -n "Checking for the yamcs server: "
        if [ -s $PID_FILE ] ; then
            pid=`cat $PID_FILE`
            if is_running $pid ; then 
                echo "running"
            else
                echo "not running"
            fi
        else 
            echo "not running"
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
