handlers = java.util.logging.ConsoleHandler

java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter = org.yamcs.logging.ConsoleFormatter

org.yamcs.level = INFO
org.yamcs.tctm.ccsds.level = FINE
org.yamcs.tctm.ccsds.srs4.level = FINE
org.yamcs.tctm.ccsds.UdpTcFrameLink.level = ALL
org.yamcs.events.EventProducer.level = ALL
