/* Generated By:JavaCC: Do not edit this line. StreamSqlParserConstants.java */
package org.yamcs.yarch.streamsql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StreamSqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_ADVANCE = 5;
  /** RegularExpression Id. */
  int K_AFAP = 6;
  /** RegularExpression Id. */
  int K_ALL = 7;
  /** RegularExpression Id. */
  int K_ALTER = 8;
  /** RegularExpression Id. */
  int K_AND = 9;
  /** RegularExpression Id. */
  int K_ANY = 10;
  /** RegularExpression Id. */
  int K_AS = 11;
  /** RegularExpression Id. */
  int K_ASC = 12;
  /** RegularExpression Id. */
  int K_BETWEEN = 13;
  /** RegularExpression Id. */
  int K_BINARY = 14;
  /** RegularExpression Id. */
  int K_BOOLEAN = 15;
  /** RegularExpression Id. */
  int K_BY = 16;
  /** RegularExpression Id. */
  int K_BYTE = 17;
  /** RegularExpression Id. */
  int K_CHAR = 18;
  /** RegularExpression Id. */
  int K_CLOSE = 19;
  /** RegularExpression Id. */
  int K_COLUMN_FAMILY = 20;
  /** RegularExpression Id. */
  int K_COMPRESSED = 21;
  /** RegularExpression Id. */
  int K_CREATE = 22;
  /** RegularExpression Id. */
  int K_CURRENT = 23;
  /** RegularExpression Id. */
  int K_DATABASES = 24;
  /** RegularExpression Id. */
  int K_DATADIR = 25;
  /** RegularExpression Id. */
  int K_DATE = 26;
  /** RegularExpression Id. */
  int K_DECIMAL = 27;
  /** RegularExpression Id. */
  int K_DELETE = 28;
  /** RegularExpression Id. */
  int K_DESC = 29;
  /** RegularExpression Id. */
  int K_DESCRIBE = 30;
  /** RegularExpression Id. */
  int K_DISTINCT = 31;
  /** RegularExpression Id. */
  int K_DOUBLE = 32;
  /** RegularExpression Id. */
  int K_DROP = 33;
  /** RegularExpression Id. */
  int K_ENGINE = 34;
  /** RegularExpression Id. */
  int K_ENGINES = 35;
  /** RegularExpression Id. */
  int K_ENUM = 36;
  /** RegularExpression Id. */
  int K_ESCAPE = 37;
  /** RegularExpression Id. */
  int K_EXISTS = 38;
  /** RegularExpression Id. */
  int K_FIXED_DELAY = 39;
  /** RegularExpression Id. */
  int K_FLOAT = 40;
  /** RegularExpression Id. */
  int K_FROM = 41;
  /** RegularExpression Id. */
  int K_HAVING = 42;
  /** RegularExpression Id. */
  int K_HISTOGRAM = 43;
  /** RegularExpression Id. */
  int K_IF = 44;
  /** RegularExpression Id. */
  int K_IN = 45;
  /** RegularExpression Id. */
  int K_IN_KEY = 46;
  /** RegularExpression Id. */
  int K_INPUT = 47;
  /** RegularExpression Id. */
  int K_INDEX = 48;
  /** RegularExpression Id. */
  int K_INSERT = 49;
  /** RegularExpression Id. */
  int K_INSERT_APPEND = 50;
  /** RegularExpression Id. */
  int K_INT = 51;
  /** RegularExpression Id. */
  int K_INTO = 52;
  /** RegularExpression Id. */
  int K_IS = 53;
  /** RegularExpression Id. */
  int K_KEY = 54;
  /** RegularExpression Id. */
  int K_LIKE = 55;
  /** RegularExpression Id. */
  int K_LIMIT = 56;
  /** RegularExpression Id. */
  int K_MERGE = 57;
  /** RegularExpression Id. */
  int K_MOD = 58;
  /** RegularExpression Id. */
  int K_NOT = 59;
  /** RegularExpression Id. */
  int K_NOFOLLOW = 60;
  /** RegularExpression Id. */
  int K_NULL = 61;
  /** RegularExpression Id. */
  int K_NULLS = 62;
  /** RegularExpression Id. */
  int K_ON = 63;
  /** RegularExpression Id. */
  int K_ONLY = 64;
  /** RegularExpression Id. */
  int K_OR = 65;
  /** RegularExpression Id. */
  int K_ORDER = 66;
  /** RegularExpression Id. */
  int K_ORIGINAL = 67;
  /** RegularExpression Id. */
  int K_OUT = 68;
  /** RegularExpression Id. */
  int K_OUTPUT = 69;
  /** RegularExpression Id. */
  int K_PARTITION = 70;
  /** RegularExpression Id. */
  int K_PARTITION_STORAGE = 71;
  /** RegularExpression Id. */
  int K_PORT = 72;
  /** RegularExpression Id. */
  int K_PRIMARY = 73;
  /** RegularExpression Id. */
  int K_PROTOBUF = 74;
  /** RegularExpression Id. */
  int K_RANGE = 75;
  /** RegularExpression Id. */
  int K_READ = 76;
  /** RegularExpression Id. */
  int K_REAL = 77;
  /** RegularExpression Id. */
  int K_REVERSE = 78;
  /** RegularExpression Id. */
  int K_ROW = 79;
  /** RegularExpression Id. */
  int K_ROWS = 80;
  /** RegularExpression Id. */
  int K_SAMPLE = 81;
  /** RegularExpression Id. */
  int K_SELECT = 82;
  /** RegularExpression Id. */
  int K_SET = 83;
  /** RegularExpression Id. */
  int K_SIZE = 84;
  /** RegularExpression Id. */
  int K_SHOW = 85;
  /** RegularExpression Id. */
  int K_SHRT = 86;
  /** RegularExpression Id. */
  int K_SMALLINT = 87;
  /** RegularExpression Id. */
  int K_SPEED = 88;
  /** RegularExpression Id. */
  int K_STEP_BY_STEP = 89;
  /** RegularExpression Id. */
  int K_STREAM = 90;
  /** RegularExpression Id. */
  int K_STREAMS = 91;
  /** RegularExpression Id. */
  int K_STRING = 92;
  /** RegularExpression Id. */
  int K_TABLE = 93;
  /** RegularExpression Id. */
  int K_TABLE_FORMAT = 94;
  /** RegularExpression Id. */
  int K_TABLES = 95;
  /** RegularExpression Id. */
  int K_TIME = 96;
  /** RegularExpression Id. */
  int K_TIME_AND_VALUE = 97;
  /** RegularExpression Id. */
  int K_TIMESTAMP = 98;
  /** RegularExpression Id. */
  int K_PARAMETER_VALUE = 99;
  /** RegularExpression Id. */
  int K_TUPLES = 100;
  /** RegularExpression Id. */
  int K_UNIQUE = 101;
  /** RegularExpression Id. */
  int K_UPDATE = 102;
  /** RegularExpression Id. */
  int K_UPSERT = 103;
  /** RegularExpression Id. */
  int K_UPSERT_APPEND = 104;
  /** RegularExpression Id. */
  int K_USE = 105;
  /** RegularExpression Id. */
  int K_USING = 106;
  /** RegularExpression Id. */
  int K_VALUE = 107;
  /** RegularExpression Id. */
  int K_WHEN = 108;
  /** RegularExpression Id. */
  int K_WHERE = 109;
  /** RegularExpression Id. */
  int S_INTEGER = 110;
  /** RegularExpression Id. */
  int S_FLOAT = 111;
  /** RegularExpression Id. */
  int EXPONENT = 112;
  /** RegularExpression Id. */
  int DIGIT = 113;
  /** RegularExpression Id. */
  int SIGN = 114;
  /** RegularExpression Id. */
  int S_STRING = 115;
  /** RegularExpression Id. */
  int LINE_COMMENT = 116;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 117;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 118;
  /** RegularExpression Id. */
  int LETTER = 119;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 120;
  /** RegularExpression Id. */
  int S_DOUBLE_QUOTED_IDENTIFIER = 121;
  /** RegularExpression Id. */
  int S_QMARK = 122;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"ADVANCE\"",
    "\"AFAP\"",
    "\"ALL\"",
    "\"ALTER\"",
    "\"AND\"",
    "\"ANY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"BETWEEN\"",
    "\"BINARY\"",
    "\"BOOLEAN\"",
    "\"BY\"",
    "\"BYTE\"",
    "\"CHAR\"",
    "\"CLOSE\"",
    "\"COLUMN_FAMILY\"",
    "\"COMPRESSED\"",
    "\"CREATE\"",
    "\"CURRENT\"",
    "\"DATABASES\"",
    "\"DATADIR\"",
    "\"DATE\"",
    "\"DECIMAL\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DESCRIBE\"",
    "\"DISTINCT\"",
    "\"DOUBLE\"",
    "\"DROP\"",
    "\"ENGINE\"",
    "\"ENGINES\"",
    "\"ENUM\"",
    "\"ESCAPE\"",
    "\"EXISTS\"",
    "\"FIXED_DELAY\"",
    "\"FLOAT\"",
    "\"FROM\"",
    "\"HAVING\"",
    "\"HISTOGRAM\"",
    "\"IF\"",
    "\"IN\"",
    "\"IN_KEY\"",
    "\"INPUT\"",
    "\"INDEX\"",
    "\"INSERT\"",
    "\"INSERT_APPEND\"",
    "\"INT\"",
    "\"INTO\"",
    "\"IS\"",
    "\"KEY\"",
    "\"LIKE\"",
    "\"LIMIT\"",
    "\"MERGE\"",
    "\"MOD\"",
    "\"NOT\"",
    "\"NOFOLLOW\"",
    "\"NULL\"",
    "\"NULLS\"",
    "\"ON\"",
    "\"ONLY\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"ORIGINAL\"",
    "\"OUT\"",
    "\"OUTPUT\"",
    "\"PARTITION\"",
    "\"PARTITION_STORAGE\"",
    "\"PORT\"",
    "\"PRIMARY\"",
    "\"PROTOBUF\"",
    "\"RANGE\"",
    "\"READ\"",
    "\"REAL\"",
    "\"REVERSE\"",
    "\"ROW\"",
    "\"ROWS\"",
    "\"SAMPLE\"",
    "\"SELECT\"",
    "\"SET\"",
    "\"SIZE\"",
    "\"SHOW\"",
    "\"SHORT\"",
    "\"SMALLINT\"",
    "\"SPEED\"",
    "\"STEP_BY_STEP\"",
    "\"STREAM\"",
    "\"STREAMS\"",
    "\"STRING\"",
    "\"TABLE\"",
    "\"TABLE_FORMAT\"",
    "\"TABLES\"",
    "\"TIME\"",
    "\"TIME_AND_VALUE\"",
    "\"TIMESTAMP\"",
    "\"PARAMETER_VALUE\"",
    "\"TUPLES\"",
    "\"UNIQUE\"",
    "\"UPDATE\"",
    "\"UPSERT\"",
    "\"UPSERT_APPEND\"",
    "\"USE\"",
    "\"USING\"",
    "\"VALUE\"",
    "\"WHEN\"",
    "\"WHERE\"",
    "<S_INTEGER>",
    "<S_FLOAT>",
    "<EXPONENT>",
    "<DIGIT>",
    "<SIGN>",
    "<S_STRING>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_DOUBLE_QUOTED_IDENTIFIER>",
    "\"?\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"=\"",
    "\";\"",
    "\"**\"",
    "\"+\"",
    "\"-\"",
    "\"||\"",
    "\"*\"",
    "\"/\"",
    "\"!\"",
    "\">\"",
    "\"<\"",
    "\"=>\"",
    "\"[\"",
    "\"]\"",
  };

}
