/* Generated By:JavaCC: Do not edit this line. StreamSqlParserConstants.java */
package org.yamcs.yarch.streamsql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StreamSqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_ADVANCE = 5;
  /** RegularExpression Id. */
  int K_AFAP = 6;
  /** RegularExpression Id. */
  int K_ALL = 7;
  /** RegularExpression Id. */
  int K_ALTER = 8;
  /** RegularExpression Id. */
  int K_AND = 9;
  /** RegularExpression Id. */
  int K_ANY = 10;
  /** RegularExpression Id. */
  int K_ARRAY = 11;
  /** RegularExpression Id. */
  int K_AS = 12;
  /** RegularExpression Id. */
  int K_ASC = 13;
  /** RegularExpression Id. */
  int K_AUTO_INCREMENT = 14;
  /** RegularExpression Id. */
  int K_BETWEEN = 15;
  /** RegularExpression Id. */
  int K_BOOLEAN = 16;
  /** RegularExpression Id. */
  int K_BY = 17;
  /** RegularExpression Id. */
  int K_BYTE = 18;
  /** RegularExpression Id. */
  int K_CHAR = 19;
  /** RegularExpression Id. */
  int K_CLOSE = 20;
  /** RegularExpression Id. */
  int K_COLUMN_FAMILY = 21;
  /** RegularExpression Id. */
  int K_COMPRESSED = 22;
  /** RegularExpression Id. */
  int K_CREATE = 23;
  /** RegularExpression Id. */
  int K_CURRENT = 24;
  /** RegularExpression Id. */
  int K_DATABASES = 25;
  /** RegularExpression Id. */
  int K_DATE = 26;
  /** RegularExpression Id. */
  int K_DECIMAL = 27;
  /** RegularExpression Id. */
  int K_DELETE = 28;
  /** RegularExpression Id. */
  int K_DESC = 29;
  /** RegularExpression Id. */
  int K_DESCRIBE = 30;
  /** RegularExpression Id. */
  int K_DISTINCT = 31;
  /** RegularExpression Id. */
  int K_DOUBLE = 32;
  /** RegularExpression Id. */
  int K_DROP = 33;
  /** RegularExpression Id. */
  int K_ENGINE = 34;
  /** RegularExpression Id. */
  int K_ENGINES = 35;
  /** RegularExpression Id. */
  int K_ENUM = 36;
  /** RegularExpression Id. */
  int K_ESCAPE = 37;
  /** RegularExpression Id. */
  int K_EXISTS = 38;
  /** RegularExpression Id. */
  int K_FIXED_DELAY = 39;
  /** RegularExpression Id. */
  int K_FLOAT = 40;
  /** RegularExpression Id. */
  int K_FROM = 41;
  /** RegularExpression Id. */
  int K_HAVING = 42;
  /** RegularExpression Id. */
  int K_HISTOGRAM = 43;
  /** RegularExpression Id. */
  int K_IF = 44;
  /** RegularExpression Id. */
  int K_IN = 45;
  /** RegularExpression Id. */
  int K_IN_KEY = 46;
  /** RegularExpression Id. */
  int K_INPUT = 47;
  /** RegularExpression Id. */
  int K_INDEX = 48;
  /** RegularExpression Id. */
  int K_INSERT = 49;
  /** RegularExpression Id. */
  int K_INSERT_APPEND = 50;
  /** RegularExpression Id. */
  int K_INT = 51;
  /** RegularExpression Id. */
  int K_INTO = 52;
  /** RegularExpression Id. */
  int K_IS = 53;
  /** RegularExpression Id. */
  int K_KEY = 54;
  /** RegularExpression Id. */
  int K_LIKE = 55;
  /** RegularExpression Id. */
  int K_LIMIT = 56;
  /** RegularExpression Id. */
  int K_LOAD = 57;
  /** RegularExpression Id. */
  int K_LONG = 58;
  /** RegularExpression Id. */
  int K_MERGE = 59;
  /** RegularExpression Id. */
  int K_MOD = 60;
  /** RegularExpression Id. */
  int K_NOT = 61;
  /** RegularExpression Id. */
  int K_NOFOLLOW = 62;
  /** RegularExpression Id. */
  int K_NULL = 63;
  /** RegularExpression Id. */
  int K_NULLS = 64;
  /** RegularExpression Id. */
  int K_ON = 65;
  /** RegularExpression Id. */
  int K_ONLY = 66;
  /** RegularExpression Id. */
  int K_OR = 67;
  /** RegularExpression Id. */
  int K_ORDER = 68;
  /** RegularExpression Id. */
  int K_ORIGINAL = 69;
  /** RegularExpression Id. */
  int K_OUT = 70;
  /** RegularExpression Id. */
  int K_OUTPUT = 71;
  /** RegularExpression Id. */
  int K_PARTITION = 72;
  /** RegularExpression Id. */
  int K_PORT = 73;
  /** RegularExpression Id. */
  int K_PRIMARY = 74;
  /** RegularExpression Id. */
  int K_PROTOBUF = 75;
  /** RegularExpression Id. */
  int K_RANGE = 76;
  /** RegularExpression Id. */
  int K_READ = 77;
  /** RegularExpression Id. */
  int K_REAL = 78;
  /** RegularExpression Id. */
  int K_RENAME = 79;
  /** RegularExpression Id. */
  int K_RESTART = 80;
  /** RegularExpression Id. */
  int K_REVERSE = 81;
  /** RegularExpression Id. */
  int K_ROW = 82;
  /** RegularExpression Id. */
  int K_ROWS = 83;
  /** RegularExpression Id. */
  int K_SAMPLE = 84;
  /** RegularExpression Id. */
  int K_SELECT = 85;
  /** RegularExpression Id. */
  int K_SEQUENCE = 86;
  /** RegularExpression Id. */
  int K_SET = 87;
  /** RegularExpression Id. */
  int K_SIZE = 88;
  /** RegularExpression Id. */
  int K_SHOW = 89;
  /** RegularExpression Id. */
  int K_SHRT = 90;
  /** RegularExpression Id. */
  int K_SMALLINT = 91;
  /** RegularExpression Id. */
  int K_SEQUENCES = 92;
  /** RegularExpression Id. */
  int K_STREAM = 93;
  /** RegularExpression Id. */
  int K_STREAMS = 94;
  /** RegularExpression Id. */
  int K_STRING = 95;
  /** RegularExpression Id. */
  int K_TABLE = 96;
  /** RegularExpression Id. */
  int K_TABLE_FORMAT = 97;
  /** RegularExpression Id. */
  int K_TABLES = 98;
  /** RegularExpression Id. */
  int K_TABLESPACE = 99;
  /** RegularExpression Id. */
  int K_TIME = 100;
  /** RegularExpression Id. */
  int K_TIME_AND_VALUE = 101;
  /** RegularExpression Id. */
  int K_TO = 102;
  /** RegularExpression Id. */
  int K_TUPLES = 103;
  /** RegularExpression Id. */
  int K_UNIQUE = 104;
  /** RegularExpression Id. */
  int K_UPDATE = 105;
  /** RegularExpression Id. */
  int K_UPSERT = 106;
  /** RegularExpression Id. */
  int K_UPSERT_APPEND = 107;
  /** RegularExpression Id. */
  int K_USE = 108;
  /** RegularExpression Id. */
  int K_USING = 109;
  /** RegularExpression Id. */
  int K_VALUE = 110;
  /** RegularExpression Id. */
  int K_VALUES = 111;
  /** RegularExpression Id. */
  int K_WHEN = 112;
  /** RegularExpression Id. */
  int K_WHERE = 113;
  /** RegularExpression Id. */
  int K_WITH = 114;
  /** RegularExpression Id. */
  int S_INTEGER = 115;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 116;
  /** RegularExpression Id. */
  int HEX_LITERAL = 117;
  /** RegularExpression Id. */
  int S_FLOAT = 118;
  /** RegularExpression Id. */
  int EXPONENT = 119;
  /** RegularExpression Id. */
  int DIGIT = 120;
  /** RegularExpression Id. */
  int HEX_DIGIT = 121;
  /** RegularExpression Id. */
  int SIGN = 122;
  /** RegularExpression Id. */
  int S_STRING = 123;
  /** RegularExpression Id. */
  int LINE_COMMENT = 124;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 125;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 126;
  /** RegularExpression Id. */
  int LETTER = 127;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 128;
  /** RegularExpression Id. */
  int S_DOUBLE_QUOTED_IDENTIFIER = 129;
  /** RegularExpression Id. */
  int S_QMARK = 130;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"ADVANCE\"",
    "\"AFAP\"",
    "\"ALL\"",
    "\"ALTER\"",
    "\"AND\"",
    "\"ANY\"",
    "\"ARRAY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"AUTO_INCREMENT\"",
    "\"BETWEEN\"",
    "\"BOOLEAN\"",
    "\"BY\"",
    "\"BYTE\"",
    "\"CHAR\"",
    "\"CLOSE\"",
    "\"COLUMN_FAMILY\"",
    "\"COMPRESSED\"",
    "\"CREATE\"",
    "\"CURRENT\"",
    "\"DATABASES\"",
    "\"DATE\"",
    "\"DECIMAL\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DESCRIBE\"",
    "\"DISTINCT\"",
    "\"DOUBLE\"",
    "\"DROP\"",
    "\"ENGINE\"",
    "\"ENGINES\"",
    "\"ENUM\"",
    "\"ESCAPE\"",
    "\"EXISTS\"",
    "\"FIXED_DELAY\"",
    "\"FLOAT\"",
    "\"FROM\"",
    "\"HAVING\"",
    "\"HISTOGRAM\"",
    "\"IF\"",
    "\"IN\"",
    "\"IN_KEY\"",
    "\"INPUT\"",
    "\"INDEX\"",
    "\"INSERT\"",
    "\"INSERT_APPEND\"",
    "\"INT\"",
    "\"INTO\"",
    "\"IS\"",
    "\"KEY\"",
    "\"LIKE\"",
    "\"LIMIT\"",
    "\"LOAD\"",
    "\"LONG\"",
    "\"MERGE\"",
    "\"MOD\"",
    "\"NOT\"",
    "\"NOFOLLOW\"",
    "\"NULL\"",
    "\"NULLS\"",
    "\"ON\"",
    "\"ONLY\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"ORIGINAL\"",
    "\"OUT\"",
    "\"OUTPUT\"",
    "\"PARTITION\"",
    "\"PORT\"",
    "\"PRIMARY\"",
    "\"PROTOBUF\"",
    "\"RANGE\"",
    "\"READ\"",
    "\"REAL\"",
    "\"RENAME\"",
    "\"RESTART\"",
    "\"REVERSE\"",
    "\"ROW\"",
    "\"ROWS\"",
    "\"SAMPLE\"",
    "\"SELECT\"",
    "\"SEQUENCE\"",
    "\"SET\"",
    "\"SIZE\"",
    "\"SHOW\"",
    "\"SHORT\"",
    "\"SMALLINT\"",
    "\"SEQUENCES\"",
    "\"STREAM\"",
    "\"STREAMS\"",
    "\"STRING\"",
    "\"TABLE\"",
    "\"TABLE_FORMAT\"",
    "\"TABLES\"",
    "\"TABLESPACE\"",
    "\"TIME\"",
    "\"TIME_AND_VALUE\"",
    "\"TO\"",
    "\"TUPLES\"",
    "\"UNIQUE\"",
    "\"UPDATE\"",
    "\"UPSERT\"",
    "\"UPSERT_APPEND\"",
    "\"USE\"",
    "\"USING\"",
    "\"VALUE\"",
    "\"VALUES\"",
    "\"WHEN\"",
    "\"WHERE\"",
    "\"WITH\"",
    "<S_INTEGER>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<S_FLOAT>",
    "<EXPONENT>",
    "<DIGIT>",
    "<HEX_DIGIT>",
    "<SIGN>",
    "<S_STRING>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_DOUBLE_QUOTED_IDENTIFIER>",
    "\"?\"",
    "\"(\"",
    "\")\"",
    "\"[]\"",
    "\",\"",
    "\"=\"",
    "\":\"",
    "\"**\"",
    "\"+\"",
    "\"-\"",
    "\"[\"",
    "\"]\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"<<\"",
    "\">>\"",
    "\"||\"",
    "\"*\"",
    "\"/\"",
    "\"!\"",
    "\">\"",
    "\"<\"",
    "\"=>\"",
  };

}
