/* Generated By:JavaCC: Do not edit this line. FilterParserConstants.java */
package org.yamcs.utils.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FilterParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQUAL = 5;
  /** RegularExpression Id. */
  int NOT_EQUAL = 6;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int QUOTED_STRING = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"=\"",
    "\"!=\"",
    "<STRING>",
    "<QUOTED_STRING>",
  };

}
