// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yamcs/protobuf/cfdp/cfdp.proto

package org.yamcs.protobuf;

public final class Cfdp {
  private Cfdp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code yamcs.protobuf.cfdp.TransferDirection}
   */
  public enum TransferDirection
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UPLOAD = 1;</code>
     */
    UPLOAD(1),
    /**
     * <code>DOWNLOAD = 2;</code>
     */
    DOWNLOAD(2),
    ;

    /**
     * <code>UPLOAD = 1;</code>
     */
    public static final int UPLOAD_VALUE = 1;
    /**
     * <code>DOWNLOAD = 2;</code>
     */
    public static final int DOWNLOAD_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TransferDirection valueOf(int value) {
      return forNumber(value);
    }

    public static TransferDirection forNumber(int value) {
      switch (value) {
        case 1: return UPLOAD;
        case 2: return DOWNLOAD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TransferDirection>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TransferDirection> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TransferDirection>() {
            public TransferDirection findValueByNumber(int number) {
              return TransferDirection.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.yamcs.protobuf.Cfdp.getDescriptor().getEnumTypes().get(0);
    }

    private static final TransferDirection[] VALUES = values();

    public static TransferDirection valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TransferDirection(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yamcs.protobuf.cfdp.TransferDirection)
  }

  /**
   * Protobuf enum {@code yamcs.protobuf.cfdp.TransferState}
   */
  public enum TransferState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RUNNING = 1;</code>
     */
    RUNNING(1),
    /**
     * <code>PAUSED = 2;</code>
     */
    PAUSED(2),
    /**
     * <code>FAILED = 3;</code>
     */
    FAILED(3),
    ;

    /**
     * <code>RUNNING = 1;</code>
     */
    public static final int RUNNING_VALUE = 1;
    /**
     * <code>PAUSED = 2;</code>
     */
    public static final int PAUSED_VALUE = 2;
    /**
     * <code>FAILED = 3;</code>
     */
    public static final int FAILED_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TransferState valueOf(int value) {
      return forNumber(value);
    }

    public static TransferState forNumber(int value) {
      switch (value) {
        case 1: return RUNNING;
        case 2: return PAUSED;
        case 3: return FAILED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TransferState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TransferState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TransferState>() {
            public TransferState findValueByNumber(int number) {
              return TransferState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.yamcs.protobuf.Cfdp.getDescriptor().getEnumTypes().get(1);
    }

    private static final TransferState[] VALUES = values();

    public static TransferState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TransferState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:yamcs.protobuf.cfdp.TransferState)
  }

  public interface TransferStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:yamcs.protobuf.cfdp.TransferStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 transferId = 1;</code>
     */
    boolean hasTransferId();
    /**
     * <code>optional uint64 transferId = 1;</code>
     */
    long getTransferId();

    /**
     * <code>optional .yamcs.protobuf.cfdp.TransferState state = 2;</code>
     */
    boolean hasState();
    /**
     * <code>optional .yamcs.protobuf.cfdp.TransferState state = 2;</code>
     */
    org.yamcs.protobuf.Cfdp.TransferState getState();

    /**
     * <code>optional string localBucketName = 3;</code>
     */
    boolean hasLocalBucketName();
    /**
     * <code>optional string localBucketName = 3;</code>
     */
    java.lang.String getLocalBucketName();
    /**
     * <code>optional string localBucketName = 3;</code>
     */
    com.google.protobuf.ByteString
        getLocalBucketNameBytes();

    /**
     * <code>optional string localObjectName = 4;</code>
     */
    boolean hasLocalObjectName();
    /**
     * <code>optional string localObjectName = 4;</code>
     */
    java.lang.String getLocalObjectName();
    /**
     * <code>optional string localObjectName = 4;</code>
     */
    com.google.protobuf.ByteString
        getLocalObjectNameBytes();

    /**
     * <code>optional string remotePath = 5;</code>
     */
    boolean hasRemotePath();
    /**
     * <code>optional string remotePath = 5;</code>
     */
    java.lang.String getRemotePath();
    /**
     * <code>optional string remotePath = 5;</code>
     */
    com.google.protobuf.ByteString
        getRemotePathBytes();

    /**
     * <code>optional .yamcs.protobuf.cfdp.TransferDirection direction = 6;</code>
     */
    boolean hasDirection();
    /**
     * <code>optional .yamcs.protobuf.cfdp.TransferDirection direction = 6;</code>
     */
    org.yamcs.protobuf.Cfdp.TransferDirection getDirection();

    /**
     * <code>optional uint64 totalSize = 7;</code>
     */
    boolean hasTotalSize();
    /**
     * <code>optional uint64 totalSize = 7;</code>
     */
    long getTotalSize();

    /**
     * <code>optional uint64 sizeTransferred = 8;</code>
     */
    boolean hasSizeTransferred();
    /**
     * <code>optional uint64 sizeTransferred = 8;</code>
     */
    long getSizeTransferred();
  }
  /**
   * <pre>
   *message sent as reponse to the info and also when starting a new transfer
   * </pre>
   *
   * Protobuf type {@code yamcs.protobuf.cfdp.TransferStatus}
   */
  public  static final class TransferStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:yamcs.protobuf.cfdp.TransferStatus)
      TransferStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransferStatus.newBuilder() to construct.
    private TransferStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransferStatus() {
      state_ = 1;
      localBucketName_ = "";
      localObjectName_ = "";
      remotePath_ = "";
      direction_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransferStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              transferId_ = input.readUInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              org.yamcs.protobuf.Cfdp.TransferState value = org.yamcs.protobuf.Cfdp.TransferState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                state_ = rawValue;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              localBucketName_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              localObjectName_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              remotePath_ = bs;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              org.yamcs.protobuf.Cfdp.TransferDirection value = org.yamcs.protobuf.Cfdp.TransferDirection.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                direction_ = rawValue;
              }
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              totalSize_ = input.readUInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              sizeTransferred_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.yamcs.protobuf.Cfdp.internal_static_yamcs_protobuf_cfdp_TransferStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.yamcs.protobuf.Cfdp.internal_static_yamcs_protobuf_cfdp_TransferStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.yamcs.protobuf.Cfdp.TransferStatus.class, org.yamcs.protobuf.Cfdp.TransferStatus.Builder.class);
    }

    private int bitField0_;
    public static final int TRANSFERID_FIELD_NUMBER = 1;
    private long transferId_;
    /**
     * <code>optional uint64 transferId = 1;</code>
     */
    public boolean hasTransferId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint64 transferId = 1;</code>
     */
    public long getTransferId() {
      return transferId_;
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private int state_;
    /**
     * <code>optional .yamcs.protobuf.cfdp.TransferState state = 2;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .yamcs.protobuf.cfdp.TransferState state = 2;</code>
     */
    public org.yamcs.protobuf.Cfdp.TransferState getState() {
      @SuppressWarnings("deprecation")
      org.yamcs.protobuf.Cfdp.TransferState result = org.yamcs.protobuf.Cfdp.TransferState.valueOf(state_);
      return result == null ? org.yamcs.protobuf.Cfdp.TransferState.RUNNING : result;
    }

    public static final int LOCALBUCKETNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object localBucketName_;
    /**
     * <code>optional string localBucketName = 3;</code>
     */
    public boolean hasLocalBucketName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string localBucketName = 3;</code>
     */
    public java.lang.String getLocalBucketName() {
      java.lang.Object ref = localBucketName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localBucketName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string localBucketName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLocalBucketNameBytes() {
      java.lang.Object ref = localBucketName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localBucketName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCALOBJECTNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object localObjectName_;
    /**
     * <code>optional string localObjectName = 4;</code>
     */
    public boolean hasLocalObjectName() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string localObjectName = 4;</code>
     */
    public java.lang.String getLocalObjectName() {
      java.lang.Object ref = localObjectName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localObjectName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string localObjectName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLocalObjectNameBytes() {
      java.lang.Object ref = localObjectName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localObjectName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMOTEPATH_FIELD_NUMBER = 5;
    private volatile java.lang.Object remotePath_;
    /**
     * <code>optional string remotePath = 5;</code>
     */
    public boolean hasRemotePath() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string remotePath = 5;</code>
     */
    public java.lang.String getRemotePath() {
      java.lang.Object ref = remotePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          remotePath_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string remotePath = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRemotePathBytes() {
      java.lang.Object ref = remotePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        remotePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECTION_FIELD_NUMBER = 6;
    private int direction_;
    /**
     * <code>optional .yamcs.protobuf.cfdp.TransferDirection direction = 6;</code>
     */
    public boolean hasDirection() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .yamcs.protobuf.cfdp.TransferDirection direction = 6;</code>
     */
    public org.yamcs.protobuf.Cfdp.TransferDirection getDirection() {
      @SuppressWarnings("deprecation")
      org.yamcs.protobuf.Cfdp.TransferDirection result = org.yamcs.protobuf.Cfdp.TransferDirection.valueOf(direction_);
      return result == null ? org.yamcs.protobuf.Cfdp.TransferDirection.UPLOAD : result;
    }

    public static final int TOTALSIZE_FIELD_NUMBER = 7;
    private long totalSize_;
    /**
     * <code>optional uint64 totalSize = 7;</code>
     */
    public boolean hasTotalSize() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional uint64 totalSize = 7;</code>
     */
    public long getTotalSize() {
      return totalSize_;
    }

    public static final int SIZETRANSFERRED_FIELD_NUMBER = 8;
    private long sizeTransferred_;
    /**
     * <code>optional uint64 sizeTransferred = 8;</code>
     */
    public boolean hasSizeTransferred() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional uint64 sizeTransferred = 8;</code>
     */
    public long getSizeTransferred() {
      return sizeTransferred_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, transferId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, state_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, localBucketName_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, localObjectName_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, remotePath_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeEnum(6, direction_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeUInt64(7, totalSize_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeUInt64(8, sizeTransferred_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, transferId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, state_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, localBucketName_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, localObjectName_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, remotePath_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, direction_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, totalSize_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, sizeTransferred_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.yamcs.protobuf.Cfdp.TransferStatus)) {
        return super.equals(obj);
      }
      org.yamcs.protobuf.Cfdp.TransferStatus other = (org.yamcs.protobuf.Cfdp.TransferStatus) obj;

      if (hasTransferId() != other.hasTransferId()) return false;
      if (hasTransferId()) {
        if (getTransferId()
            != other.getTransferId()) return false;
      }
      if (hasState() != other.hasState()) return false;
      if (hasState()) {
        if (state_ != other.state_) return false;
      }
      if (hasLocalBucketName() != other.hasLocalBucketName()) return false;
      if (hasLocalBucketName()) {
        if (!getLocalBucketName()
            .equals(other.getLocalBucketName())) return false;
      }
      if (hasLocalObjectName() != other.hasLocalObjectName()) return false;
      if (hasLocalObjectName()) {
        if (!getLocalObjectName()
            .equals(other.getLocalObjectName())) return false;
      }
      if (hasRemotePath() != other.hasRemotePath()) return false;
      if (hasRemotePath()) {
        if (!getRemotePath()
            .equals(other.getRemotePath())) return false;
      }
      if (hasDirection() != other.hasDirection()) return false;
      if (hasDirection()) {
        if (direction_ != other.direction_) return false;
      }
      if (hasTotalSize() != other.hasTotalSize()) return false;
      if (hasTotalSize()) {
        if (getTotalSize()
            != other.getTotalSize()) return false;
      }
      if (hasSizeTransferred() != other.hasSizeTransferred()) return false;
      if (hasSizeTransferred()) {
        if (getSizeTransferred()
            != other.getSizeTransferred()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTransferId()) {
        hash = (37 * hash) + TRANSFERID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTransferId());
      }
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + state_;
      }
      if (hasLocalBucketName()) {
        hash = (37 * hash) + LOCALBUCKETNAME_FIELD_NUMBER;
        hash = (53 * hash) + getLocalBucketName().hashCode();
      }
      if (hasLocalObjectName()) {
        hash = (37 * hash) + LOCALOBJECTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getLocalObjectName().hashCode();
      }
      if (hasRemotePath()) {
        hash = (37 * hash) + REMOTEPATH_FIELD_NUMBER;
        hash = (53 * hash) + getRemotePath().hashCode();
      }
      if (hasDirection()) {
        hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
        hash = (53 * hash) + direction_;
      }
      if (hasTotalSize()) {
        hash = (37 * hash) + TOTALSIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTotalSize());
      }
      if (hasSizeTransferred()) {
        hash = (37 * hash) + SIZETRANSFERRED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSizeTransferred());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.yamcs.protobuf.Cfdp.TransferStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.yamcs.protobuf.Cfdp.TransferStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.yamcs.protobuf.Cfdp.TransferStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.yamcs.protobuf.Cfdp.TransferStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.yamcs.protobuf.Cfdp.TransferStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.yamcs.protobuf.Cfdp.TransferStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.yamcs.protobuf.Cfdp.TransferStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.yamcs.protobuf.Cfdp.TransferStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.yamcs.protobuf.Cfdp.TransferStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.yamcs.protobuf.Cfdp.TransferStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.yamcs.protobuf.Cfdp.TransferStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.yamcs.protobuf.Cfdp.TransferStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.yamcs.protobuf.Cfdp.TransferStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *message sent as reponse to the info and also when starting a new transfer
     * </pre>
     *
     * Protobuf type {@code yamcs.protobuf.cfdp.TransferStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:yamcs.protobuf.cfdp.TransferStatus)
        org.yamcs.protobuf.Cfdp.TransferStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.yamcs.protobuf.Cfdp.internal_static_yamcs_protobuf_cfdp_TransferStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.yamcs.protobuf.Cfdp.internal_static_yamcs_protobuf_cfdp_TransferStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.yamcs.protobuf.Cfdp.TransferStatus.class, org.yamcs.protobuf.Cfdp.TransferStatus.Builder.class);
      }

      // Construct using org.yamcs.protobuf.Cfdp.TransferStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        transferId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        localBucketName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        localObjectName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        remotePath_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        direction_ = 1;
        bitField0_ = (bitField0_ & ~0x00000020);
        totalSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        sizeTransferred_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.yamcs.protobuf.Cfdp.internal_static_yamcs_protobuf_cfdp_TransferStatus_descriptor;
      }

      @java.lang.Override
      public org.yamcs.protobuf.Cfdp.TransferStatus getDefaultInstanceForType() {
        return org.yamcs.protobuf.Cfdp.TransferStatus.getDefaultInstance();
      }

      @java.lang.Override
      public org.yamcs.protobuf.Cfdp.TransferStatus build() {
        org.yamcs.protobuf.Cfdp.TransferStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.yamcs.protobuf.Cfdp.TransferStatus buildPartial() {
        org.yamcs.protobuf.Cfdp.TransferStatus result = new org.yamcs.protobuf.Cfdp.TransferStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.transferId_ = transferId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.localBucketName_ = localBucketName_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.localObjectName_ = localObjectName_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.remotePath_ = remotePath_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.direction_ = direction_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.totalSize_ = totalSize_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.sizeTransferred_ = sizeTransferred_;
          to_bitField0_ |= 0x00000080;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.yamcs.protobuf.Cfdp.TransferStatus) {
          return mergeFrom((org.yamcs.protobuf.Cfdp.TransferStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.yamcs.protobuf.Cfdp.TransferStatus other) {
        if (other == org.yamcs.protobuf.Cfdp.TransferStatus.getDefaultInstance()) return this;
        if (other.hasTransferId()) {
          setTransferId(other.getTransferId());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasLocalBucketName()) {
          bitField0_ |= 0x00000004;
          localBucketName_ = other.localBucketName_;
          onChanged();
        }
        if (other.hasLocalObjectName()) {
          bitField0_ |= 0x00000008;
          localObjectName_ = other.localObjectName_;
          onChanged();
        }
        if (other.hasRemotePath()) {
          bitField0_ |= 0x00000010;
          remotePath_ = other.remotePath_;
          onChanged();
        }
        if (other.hasDirection()) {
          setDirection(other.getDirection());
        }
        if (other.hasTotalSize()) {
          setTotalSize(other.getTotalSize());
        }
        if (other.hasSizeTransferred()) {
          setSizeTransferred(other.getSizeTransferred());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.yamcs.protobuf.Cfdp.TransferStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.yamcs.protobuf.Cfdp.TransferStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long transferId_ ;
      /**
       * <code>optional uint64 transferId = 1;</code>
       */
      public boolean hasTransferId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint64 transferId = 1;</code>
       */
      public long getTransferId() {
        return transferId_;
      }
      /**
       * <code>optional uint64 transferId = 1;</code>
       */
      public Builder setTransferId(long value) {
        bitField0_ |= 0x00000001;
        transferId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 transferId = 1;</code>
       */
      public Builder clearTransferId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        transferId_ = 0L;
        onChanged();
        return this;
      }

      private int state_ = 1;
      /**
       * <code>optional .yamcs.protobuf.cfdp.TransferState state = 2;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .yamcs.protobuf.cfdp.TransferState state = 2;</code>
       */
      public org.yamcs.protobuf.Cfdp.TransferState getState() {
        @SuppressWarnings("deprecation")
        org.yamcs.protobuf.Cfdp.TransferState result = org.yamcs.protobuf.Cfdp.TransferState.valueOf(state_);
        return result == null ? org.yamcs.protobuf.Cfdp.TransferState.RUNNING : result;
      }
      /**
       * <code>optional .yamcs.protobuf.cfdp.TransferState state = 2;</code>
       */
      public Builder setState(org.yamcs.protobuf.Cfdp.TransferState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .yamcs.protobuf.cfdp.TransferState state = 2;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object localBucketName_ = "";
      /**
       * <code>optional string localBucketName = 3;</code>
       */
      public boolean hasLocalBucketName() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string localBucketName = 3;</code>
       */
      public java.lang.String getLocalBucketName() {
        java.lang.Object ref = localBucketName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            localBucketName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string localBucketName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLocalBucketNameBytes() {
        java.lang.Object ref = localBucketName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localBucketName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string localBucketName = 3;</code>
       */
      public Builder setLocalBucketName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        localBucketName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string localBucketName = 3;</code>
       */
      public Builder clearLocalBucketName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        localBucketName_ = getDefaultInstance().getLocalBucketName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string localBucketName = 3;</code>
       */
      public Builder setLocalBucketNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        localBucketName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object localObjectName_ = "";
      /**
       * <code>optional string localObjectName = 4;</code>
       */
      public boolean hasLocalObjectName() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string localObjectName = 4;</code>
       */
      public java.lang.String getLocalObjectName() {
        java.lang.Object ref = localObjectName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            localObjectName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string localObjectName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLocalObjectNameBytes() {
        java.lang.Object ref = localObjectName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localObjectName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string localObjectName = 4;</code>
       */
      public Builder setLocalObjectName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        localObjectName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string localObjectName = 4;</code>
       */
      public Builder clearLocalObjectName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        localObjectName_ = getDefaultInstance().getLocalObjectName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string localObjectName = 4;</code>
       */
      public Builder setLocalObjectNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        localObjectName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object remotePath_ = "";
      /**
       * <code>optional string remotePath = 5;</code>
       */
      public boolean hasRemotePath() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string remotePath = 5;</code>
       */
      public java.lang.String getRemotePath() {
        java.lang.Object ref = remotePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            remotePath_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string remotePath = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRemotePathBytes() {
        java.lang.Object ref = remotePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          remotePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string remotePath = 5;</code>
       */
      public Builder setRemotePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        remotePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string remotePath = 5;</code>
       */
      public Builder clearRemotePath() {
        bitField0_ = (bitField0_ & ~0x00000010);
        remotePath_ = getDefaultInstance().getRemotePath();
        onChanged();
        return this;
      }
      /**
       * <code>optional string remotePath = 5;</code>
       */
      public Builder setRemotePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        remotePath_ = value;
        onChanged();
        return this;
      }

      private int direction_ = 1;
      /**
       * <code>optional .yamcs.protobuf.cfdp.TransferDirection direction = 6;</code>
       */
      public boolean hasDirection() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional .yamcs.protobuf.cfdp.TransferDirection direction = 6;</code>
       */
      public org.yamcs.protobuf.Cfdp.TransferDirection getDirection() {
        @SuppressWarnings("deprecation")
        org.yamcs.protobuf.Cfdp.TransferDirection result = org.yamcs.protobuf.Cfdp.TransferDirection.valueOf(direction_);
        return result == null ? org.yamcs.protobuf.Cfdp.TransferDirection.UPLOAD : result;
      }
      /**
       * <code>optional .yamcs.protobuf.cfdp.TransferDirection direction = 6;</code>
       */
      public Builder setDirection(org.yamcs.protobuf.Cfdp.TransferDirection value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        direction_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .yamcs.protobuf.cfdp.TransferDirection direction = 6;</code>
       */
      public Builder clearDirection() {
        bitField0_ = (bitField0_ & ~0x00000020);
        direction_ = 1;
        onChanged();
        return this;
      }

      private long totalSize_ ;
      /**
       * <code>optional uint64 totalSize = 7;</code>
       */
      public boolean hasTotalSize() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional uint64 totalSize = 7;</code>
       */
      public long getTotalSize() {
        return totalSize_;
      }
      /**
       * <code>optional uint64 totalSize = 7;</code>
       */
      public Builder setTotalSize(long value) {
        bitField0_ |= 0x00000040;
        totalSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 totalSize = 7;</code>
       */
      public Builder clearTotalSize() {
        bitField0_ = (bitField0_ & ~0x00000040);
        totalSize_ = 0L;
        onChanged();
        return this;
      }

      private long sizeTransferred_ ;
      /**
       * <code>optional uint64 sizeTransferred = 8;</code>
       */
      public boolean hasSizeTransferred() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional uint64 sizeTransferred = 8;</code>
       */
      public long getSizeTransferred() {
        return sizeTransferred_;
      }
      /**
       * <code>optional uint64 sizeTransferred = 8;</code>
       */
      public Builder setSizeTransferred(long value) {
        bitField0_ |= 0x00000080;
        sizeTransferred_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 sizeTransferred = 8;</code>
       */
      public Builder clearSizeTransferred() {
        bitField0_ = (bitField0_ & ~0x00000080);
        sizeTransferred_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:yamcs.protobuf.cfdp.TransferStatus)
    }

    // @@protoc_insertion_point(class_scope:yamcs.protobuf.cfdp.TransferStatus)
    private static final org.yamcs.protobuf.Cfdp.TransferStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.yamcs.protobuf.Cfdp.TransferStatus();
    }

    public static org.yamcs.protobuf.Cfdp.TransferStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TransferStatus>
        PARSER = new com.google.protobuf.AbstractParser<TransferStatus>() {
      @java.lang.Override
      public TransferStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransferStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransferStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransferStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.yamcs.protobuf.Cfdp.TransferStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListTransfersResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:yamcs.protobuf.cfdp.ListTransfersResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
     */
    java.util.List<org.yamcs.protobuf.Cfdp.TransferStatus> 
        getTransfersList();
    /**
     * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
     */
    org.yamcs.protobuf.Cfdp.TransferStatus getTransfers(int index);
    /**
     * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
     */
    int getTransfersCount();
    /**
     * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
     */
    java.util.List<? extends org.yamcs.protobuf.Cfdp.TransferStatusOrBuilder> 
        getTransfersOrBuilderList();
    /**
     * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
     */
    org.yamcs.protobuf.Cfdp.TransferStatusOrBuilder getTransfersOrBuilder(
        int index);
  }
  /**
   * <pre>
   *message sent as the response to the list transfers
   * </pre>
   *
   * Protobuf type {@code yamcs.protobuf.cfdp.ListTransfersResponse}
   */
  public  static final class ListTransfersResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:yamcs.protobuf.cfdp.ListTransfersResponse)
      ListTransfersResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ListTransfersResponse.newBuilder() to construct.
    private ListTransfersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListTransfersResponse() {
      transfers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ListTransfersResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                transfers_ = new java.util.ArrayList<org.yamcs.protobuf.Cfdp.TransferStatus>();
                mutable_bitField0_ |= 0x00000001;
              }
              transfers_.add(
                  input.readMessage(org.yamcs.protobuf.Cfdp.TransferStatus.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          transfers_ = java.util.Collections.unmodifiableList(transfers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.yamcs.protobuf.Cfdp.internal_static_yamcs_protobuf_cfdp_ListTransfersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.yamcs.protobuf.Cfdp.internal_static_yamcs_protobuf_cfdp_ListTransfersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.yamcs.protobuf.Cfdp.ListTransfersResponse.class, org.yamcs.protobuf.Cfdp.ListTransfersResponse.Builder.class);
    }

    public static final int TRANSFERS_FIELD_NUMBER = 1;
    private java.util.List<org.yamcs.protobuf.Cfdp.TransferStatus> transfers_;
    /**
     * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
     */
    public java.util.List<org.yamcs.protobuf.Cfdp.TransferStatus> getTransfersList() {
      return transfers_;
    }
    /**
     * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
     */
    public java.util.List<? extends org.yamcs.protobuf.Cfdp.TransferStatusOrBuilder> 
        getTransfersOrBuilderList() {
      return transfers_;
    }
    /**
     * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
     */
    public int getTransfersCount() {
      return transfers_.size();
    }
    /**
     * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
     */
    public org.yamcs.protobuf.Cfdp.TransferStatus getTransfers(int index) {
      return transfers_.get(index);
    }
    /**
     * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
     */
    public org.yamcs.protobuf.Cfdp.TransferStatusOrBuilder getTransfersOrBuilder(
        int index) {
      return transfers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < transfers_.size(); i++) {
        output.writeMessage(1, transfers_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < transfers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, transfers_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.yamcs.protobuf.Cfdp.ListTransfersResponse)) {
        return super.equals(obj);
      }
      org.yamcs.protobuf.Cfdp.ListTransfersResponse other = (org.yamcs.protobuf.Cfdp.ListTransfersResponse) obj;

      if (!getTransfersList()
          .equals(other.getTransfersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTransfersCount() > 0) {
        hash = (37 * hash) + TRANSFERS_FIELD_NUMBER;
        hash = (53 * hash) + getTransfersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.yamcs.protobuf.Cfdp.ListTransfersResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.yamcs.protobuf.Cfdp.ListTransfersResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.yamcs.protobuf.Cfdp.ListTransfersResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.yamcs.protobuf.Cfdp.ListTransfersResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.yamcs.protobuf.Cfdp.ListTransfersResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.yamcs.protobuf.Cfdp.ListTransfersResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.yamcs.protobuf.Cfdp.ListTransfersResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.yamcs.protobuf.Cfdp.ListTransfersResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.yamcs.protobuf.Cfdp.ListTransfersResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.yamcs.protobuf.Cfdp.ListTransfersResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.yamcs.protobuf.Cfdp.ListTransfersResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.yamcs.protobuf.Cfdp.ListTransfersResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.yamcs.protobuf.Cfdp.ListTransfersResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *message sent as the response to the list transfers
     * </pre>
     *
     * Protobuf type {@code yamcs.protobuf.cfdp.ListTransfersResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:yamcs.protobuf.cfdp.ListTransfersResponse)
        org.yamcs.protobuf.Cfdp.ListTransfersResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.yamcs.protobuf.Cfdp.internal_static_yamcs_protobuf_cfdp_ListTransfersResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.yamcs.protobuf.Cfdp.internal_static_yamcs_protobuf_cfdp_ListTransfersResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.yamcs.protobuf.Cfdp.ListTransfersResponse.class, org.yamcs.protobuf.Cfdp.ListTransfersResponse.Builder.class);
      }

      // Construct using org.yamcs.protobuf.Cfdp.ListTransfersResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTransfersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (transfersBuilder_ == null) {
          transfers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          transfersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.yamcs.protobuf.Cfdp.internal_static_yamcs_protobuf_cfdp_ListTransfersResponse_descriptor;
      }

      @java.lang.Override
      public org.yamcs.protobuf.Cfdp.ListTransfersResponse getDefaultInstanceForType() {
        return org.yamcs.protobuf.Cfdp.ListTransfersResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.yamcs.protobuf.Cfdp.ListTransfersResponse build() {
        org.yamcs.protobuf.Cfdp.ListTransfersResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.yamcs.protobuf.Cfdp.ListTransfersResponse buildPartial() {
        org.yamcs.protobuf.Cfdp.ListTransfersResponse result = new org.yamcs.protobuf.Cfdp.ListTransfersResponse(this);
        int from_bitField0_ = bitField0_;
        if (transfersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            transfers_ = java.util.Collections.unmodifiableList(transfers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.transfers_ = transfers_;
        } else {
          result.transfers_ = transfersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.yamcs.protobuf.Cfdp.ListTransfersResponse) {
          return mergeFrom((org.yamcs.protobuf.Cfdp.ListTransfersResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.yamcs.protobuf.Cfdp.ListTransfersResponse other) {
        if (other == org.yamcs.protobuf.Cfdp.ListTransfersResponse.getDefaultInstance()) return this;
        if (transfersBuilder_ == null) {
          if (!other.transfers_.isEmpty()) {
            if (transfers_.isEmpty()) {
              transfers_ = other.transfers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTransfersIsMutable();
              transfers_.addAll(other.transfers_);
            }
            onChanged();
          }
        } else {
          if (!other.transfers_.isEmpty()) {
            if (transfersBuilder_.isEmpty()) {
              transfersBuilder_.dispose();
              transfersBuilder_ = null;
              transfers_ = other.transfers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              transfersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTransfersFieldBuilder() : null;
            } else {
              transfersBuilder_.addAllMessages(other.transfers_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.yamcs.protobuf.Cfdp.ListTransfersResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.yamcs.protobuf.Cfdp.ListTransfersResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.yamcs.protobuf.Cfdp.TransferStatus> transfers_ =
        java.util.Collections.emptyList();
      private void ensureTransfersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          transfers_ = new java.util.ArrayList<org.yamcs.protobuf.Cfdp.TransferStatus>(transfers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.yamcs.protobuf.Cfdp.TransferStatus, org.yamcs.protobuf.Cfdp.TransferStatus.Builder, org.yamcs.protobuf.Cfdp.TransferStatusOrBuilder> transfersBuilder_;

      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public java.util.List<org.yamcs.protobuf.Cfdp.TransferStatus> getTransfersList() {
        if (transfersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(transfers_);
        } else {
          return transfersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public int getTransfersCount() {
        if (transfersBuilder_ == null) {
          return transfers_.size();
        } else {
          return transfersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public org.yamcs.protobuf.Cfdp.TransferStatus getTransfers(int index) {
        if (transfersBuilder_ == null) {
          return transfers_.get(index);
        } else {
          return transfersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public Builder setTransfers(
          int index, org.yamcs.protobuf.Cfdp.TransferStatus value) {
        if (transfersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransfersIsMutable();
          transfers_.set(index, value);
          onChanged();
        } else {
          transfersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public Builder setTransfers(
          int index, org.yamcs.protobuf.Cfdp.TransferStatus.Builder builderForValue) {
        if (transfersBuilder_ == null) {
          ensureTransfersIsMutable();
          transfers_.set(index, builderForValue.build());
          onChanged();
        } else {
          transfersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public Builder addTransfers(org.yamcs.protobuf.Cfdp.TransferStatus value) {
        if (transfersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransfersIsMutable();
          transfers_.add(value);
          onChanged();
        } else {
          transfersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public Builder addTransfers(
          int index, org.yamcs.protobuf.Cfdp.TransferStatus value) {
        if (transfersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTransfersIsMutable();
          transfers_.add(index, value);
          onChanged();
        } else {
          transfersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public Builder addTransfers(
          org.yamcs.protobuf.Cfdp.TransferStatus.Builder builderForValue) {
        if (transfersBuilder_ == null) {
          ensureTransfersIsMutable();
          transfers_.add(builderForValue.build());
          onChanged();
        } else {
          transfersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public Builder addTransfers(
          int index, org.yamcs.protobuf.Cfdp.TransferStatus.Builder builderForValue) {
        if (transfersBuilder_ == null) {
          ensureTransfersIsMutable();
          transfers_.add(index, builderForValue.build());
          onChanged();
        } else {
          transfersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public Builder addAllTransfers(
          java.lang.Iterable<? extends org.yamcs.protobuf.Cfdp.TransferStatus> values) {
        if (transfersBuilder_ == null) {
          ensureTransfersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, transfers_);
          onChanged();
        } else {
          transfersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public Builder clearTransfers() {
        if (transfersBuilder_ == null) {
          transfers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          transfersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public Builder removeTransfers(int index) {
        if (transfersBuilder_ == null) {
          ensureTransfersIsMutable();
          transfers_.remove(index);
          onChanged();
        } else {
          transfersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public org.yamcs.protobuf.Cfdp.TransferStatus.Builder getTransfersBuilder(
          int index) {
        return getTransfersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public org.yamcs.protobuf.Cfdp.TransferStatusOrBuilder getTransfersOrBuilder(
          int index) {
        if (transfersBuilder_ == null) {
          return transfers_.get(index);  } else {
          return transfersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public java.util.List<? extends org.yamcs.protobuf.Cfdp.TransferStatusOrBuilder> 
           getTransfersOrBuilderList() {
        if (transfersBuilder_ != null) {
          return transfersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(transfers_);
        }
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public org.yamcs.protobuf.Cfdp.TransferStatus.Builder addTransfersBuilder() {
        return getTransfersFieldBuilder().addBuilder(
            org.yamcs.protobuf.Cfdp.TransferStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public org.yamcs.protobuf.Cfdp.TransferStatus.Builder addTransfersBuilder(
          int index) {
        return getTransfersFieldBuilder().addBuilder(
            index, org.yamcs.protobuf.Cfdp.TransferStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .yamcs.protobuf.cfdp.TransferStatus transfers = 1;</code>
       */
      public java.util.List<org.yamcs.protobuf.Cfdp.TransferStatus.Builder> 
           getTransfersBuilderList() {
        return getTransfersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.yamcs.protobuf.Cfdp.TransferStatus, org.yamcs.protobuf.Cfdp.TransferStatus.Builder, org.yamcs.protobuf.Cfdp.TransferStatusOrBuilder> 
          getTransfersFieldBuilder() {
        if (transfersBuilder_ == null) {
          transfersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.yamcs.protobuf.Cfdp.TransferStatus, org.yamcs.protobuf.Cfdp.TransferStatus.Builder, org.yamcs.protobuf.Cfdp.TransferStatusOrBuilder>(
                  transfers_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          transfers_ = null;
        }
        return transfersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:yamcs.protobuf.cfdp.ListTransfersResponse)
    }

    // @@protoc_insertion_point(class_scope:yamcs.protobuf.cfdp.ListTransfersResponse)
    private static final org.yamcs.protobuf.Cfdp.ListTransfersResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.yamcs.protobuf.Cfdp.ListTransfersResponse();
    }

    public static org.yamcs.protobuf.Cfdp.ListTransfersResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ListTransfersResponse>
        PARSER = new com.google.protobuf.AbstractParser<ListTransfersResponse>() {
      @java.lang.Override
      public ListTransfersResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListTransfersResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ListTransfersResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListTransfersResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.yamcs.protobuf.Cfdp.ListTransfersResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yamcs_protobuf_cfdp_TransferStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yamcs_protobuf_cfdp_TransferStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yamcs_protobuf_cfdp_ListTransfersResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yamcs_protobuf_cfdp_ListTransfersResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036yamcs/protobuf/cfdp/cfdp.proto\022\023yamcs." +
      "protobuf.cfdp\"\204\002\n\016TransferStatus\022\022\n\ntran" +
      "sferId\030\001 \001(\004\0221\n\005state\030\002 \001(\0162\".yamcs.prot" +
      "obuf.cfdp.TransferState\022\027\n\017localBucketNa" +
      "me\030\003 \001(\t\022\027\n\017localObjectName\030\004 \001(\t\022\022\n\nrem" +
      "otePath\030\005 \001(\t\0229\n\tdirection\030\006 \001(\0162&.yamcs" +
      ".protobuf.cfdp.TransferDirection\022\021\n\ttota" +
      "lSize\030\007 \001(\004\022\027\n\017sizeTransferred\030\010 \001(\004\"O\n\025" +
      "ListTransfersResponse\0226\n\ttransfers\030\001 \003(\013" +
      "2#.yamcs.protobuf.cfdp.TransferStatus*-\n" +
      "\021TransferDirection\022\n\n\006UPLOAD\020\001\022\014\n\010DOWNLO" +
      "AD\020\002*4\n\rTransferState\022\013\n\007RUNNING\020\001\022\n\n\006PA" +
      "USED\020\002\022\n\n\006FAILED\020\003B\024\n\022org.yamcs.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_yamcs_protobuf_cfdp_TransferStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yamcs_protobuf_cfdp_TransferStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yamcs_protobuf_cfdp_TransferStatus_descriptor,
        new java.lang.String[] { "TransferId", "State", "LocalBucketName", "LocalObjectName", "RemotePath", "Direction", "TotalSize", "SizeTransferred", });
    internal_static_yamcs_protobuf_cfdp_ListTransfersResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_yamcs_protobuf_cfdp_ListTransfersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yamcs_protobuf_cfdp_ListTransfersResponse_descriptor,
        new java.lang.String[] { "Transfers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
