// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from alarms.proto

package org.yamcs.protobuf;


public final class SchemaAlarms
{

    public static final class AcknowledgeInfo
    {
        public static final org.yamcs.protobuf.SchemaAlarms.AcknowledgeInfo.MessageSchema WRITE =
            new org.yamcs.protobuf.SchemaAlarms.AcknowledgeInfo.MessageSchema();
        public static final org.yamcs.protobuf.SchemaAlarms.AcknowledgeInfo.BuilderSchema MERGE =
            new org.yamcs.protobuf.SchemaAlarms.AcknowledgeInfo.BuilderSchema();
        
        public static class MessageSchema implements io.protostuff.Schema<org.yamcs.protobuf.Alarms.AcknowledgeInfo>
        {
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.Alarms.AcknowledgeInfo message) throws java.io.IOException
            {
                if(message.hasAcknowledgedBy())
                    output.writeString(1, message.getAcknowledgedBy(), false);
                if(message.hasAcknowledgeMessage())
                    output.writeString(2, message.getAcknowledgeMessage(), false);
                if(message.hasAcknowledgeTime())
                    output.writeInt64(3, message.getAcknowledgeTime(), false);
                if(message.hasAcknowledgeTimeUTC())
                    output.writeString(4, message.getAcknowledgeTimeUTC(), false);
            }
            public boolean isInitialized(org.yamcs.protobuf.Alarms.AcknowledgeInfo message)
            {
                return message.isInitialized();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaAlarms.AcknowledgeInfo.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaAlarms.AcknowledgeInfo.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.Alarms.AcknowledgeInfo> typeClass()
            {
                return org.yamcs.protobuf.Alarms.AcknowledgeInfo.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.Alarms.AcknowledgeInfo.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.Alarms.AcknowledgeInfo.class.getName();
            }
            //unused
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.Alarms.AcknowledgeInfo message) throws java.io.IOException {}
            public org.yamcs.protobuf.Alarms.AcknowledgeInfo newMessage() { return null; }
        }
        public static class BuilderSchema implements io.protostuff.Schema<org.yamcs.protobuf.Alarms.AcknowledgeInfo.Builder>
        {
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.Alarms.AcknowledgeInfo.Builder builder) throws java.io.IOException
            {
                for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
                {
                    switch(number)
                    {
                        case 0:
                            return;
                        case 1:
                            builder.setAcknowledgedBy(input.readString());
                            break;
                        case 2:
                            builder.setAcknowledgeMessage(input.readString());
                            break;
                        case 3:
                            builder.setAcknowledgeTime(input.readInt64());
                            break;
                        case 4:
                            builder.setAcknowledgeTimeUTC(input.readString());
                            break;
                        default:
                            input.handleUnknownField(number, this);
                    }
                }
            }
            public boolean isInitialized(org.yamcs.protobuf.Alarms.AcknowledgeInfo.Builder builder)
            {
                return builder.isInitialized();
            }
            public org.yamcs.protobuf.Alarms.AcknowledgeInfo.Builder newMessage()
            {
                return org.yamcs.protobuf.Alarms.AcknowledgeInfo.newBuilder();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaAlarms.AcknowledgeInfo.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaAlarms.AcknowledgeInfo.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.Alarms.AcknowledgeInfo.Builder> typeClass()
            {
                return org.yamcs.protobuf.Alarms.AcknowledgeInfo.Builder.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.Alarms.AcknowledgeInfo.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.Alarms.AcknowledgeInfo.class.getName();
            }
            //unused
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.Alarms.AcknowledgeInfo.Builder builder) throws java.io.IOException {}
        }
        public static java.lang.String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "acknowledgedBy";
                case 2: return "acknowledgeMessage";
                case 3: return "acknowledgeTime";
                case 4: return "acknowledgeTimeUTC";
                default: return null;
            }
        }
        public static int getFieldNumber(java.lang.String name)
        {
            java.lang.Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }
        private static final java.util.HashMap<java.lang.String,java.lang.Integer> fieldMap = new java.util.HashMap<java.lang.String,java.lang.Integer>();
        static
        {
            fieldMap.put("acknowledgedBy", 1);
            fieldMap.put("acknowledgeMessage", 2);
            fieldMap.put("acknowledgeTime", 3);
            fieldMap.put("acknowledgeTimeUTC", 4);
        }
    }

    public static final class AlarmInfo
    {
        public static final org.yamcs.protobuf.SchemaAlarms.AlarmInfo.MessageSchema WRITE =
            new org.yamcs.protobuf.SchemaAlarms.AlarmInfo.MessageSchema();
        public static final org.yamcs.protobuf.SchemaAlarms.AlarmInfo.BuilderSchema MERGE =
            new org.yamcs.protobuf.SchemaAlarms.AlarmInfo.BuilderSchema();
        
        public static class MessageSchema implements io.protostuff.Schema<org.yamcs.protobuf.Alarms.AlarmInfo>
        {
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.Alarms.AlarmInfo message) throws java.io.IOException
            {
                if(message.hasId())
                    output.writeUInt32(1, message.getId(), false);
                if(message.hasType())
                    output.writeString(2, message.getType().name(), false);
                if(message.hasTriggerValue())
                    output.writeObject(3, message.getTriggerValue(), org.yamcs.protobuf.SchemaPvalue.ParameterValue.WRITE, false);

                if(message.hasMostSevereValue())
                    output.writeObject(4, message.getMostSevereValue(), org.yamcs.protobuf.SchemaPvalue.ParameterValue.WRITE, false);

                if(message.hasCurrentValue())
                    output.writeObject(5, message.getCurrentValue(), org.yamcs.protobuf.SchemaPvalue.ParameterValue.WRITE, false);

                if(message.hasViolations())
                    output.writeUInt32(6, message.getViolations(), false);
                if(message.hasAcknowledgeInfo())
                    output.writeObject(7, message.getAcknowledgeInfo(), org.yamcs.protobuf.SchemaAlarms.AcknowledgeInfo.WRITE, false);

            }
            public boolean isInitialized(org.yamcs.protobuf.Alarms.AlarmInfo message)
            {
                return message.isInitialized();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaAlarms.AlarmInfo.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaAlarms.AlarmInfo.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.Alarms.AlarmInfo> typeClass()
            {
                return org.yamcs.protobuf.Alarms.AlarmInfo.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.Alarms.AlarmInfo.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.Alarms.AlarmInfo.class.getName();
            }
            //unused
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.Alarms.AlarmInfo message) throws java.io.IOException {}
            public org.yamcs.protobuf.Alarms.AlarmInfo newMessage() { return null; }
        }
        public static class BuilderSchema implements io.protostuff.Schema<org.yamcs.protobuf.Alarms.AlarmInfo.Builder>
        {
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.Alarms.AlarmInfo.Builder builder) throws java.io.IOException
            {
                for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
                {
                    switch(number)
                    {
                        case 0:
                            return;
                        case 1:
                            builder.setId(input.readUInt32());
                            break;
                        case 2:
                            builder.setType(org.yamcs.protobuf.Alarms.AlarmInfo.Type.valueOf(input.readString()));
                            break;
                        case 3:
                            builder.setTriggerValue(input.mergeObject(org.yamcs.protobuf.Pvalue.ParameterValue.newBuilder(), org.yamcs.protobuf.SchemaPvalue.ParameterValue.MERGE));

                            break;
                        case 4:
                            builder.setMostSevereValue(input.mergeObject(org.yamcs.protobuf.Pvalue.ParameterValue.newBuilder(), org.yamcs.protobuf.SchemaPvalue.ParameterValue.MERGE));

                            break;
                        case 5:
                            builder.setCurrentValue(input.mergeObject(org.yamcs.protobuf.Pvalue.ParameterValue.newBuilder(), org.yamcs.protobuf.SchemaPvalue.ParameterValue.MERGE));

                            break;
                        case 6:
                            builder.setViolations(input.readUInt32());
                            break;
                        case 7:
                            builder.setAcknowledgeInfo(input.mergeObject(org.yamcs.protobuf.Alarms.AcknowledgeInfo.newBuilder(), org.yamcs.protobuf.SchemaAlarms.AcknowledgeInfo.MERGE));

                            break;
                        default:
                            input.handleUnknownField(number, this);
                    }
                }
            }
            public boolean isInitialized(org.yamcs.protobuf.Alarms.AlarmInfo.Builder builder)
            {
                return builder.isInitialized();
            }
            public org.yamcs.protobuf.Alarms.AlarmInfo.Builder newMessage()
            {
                return org.yamcs.protobuf.Alarms.AlarmInfo.newBuilder();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaAlarms.AlarmInfo.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaAlarms.AlarmInfo.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.Alarms.AlarmInfo.Builder> typeClass()
            {
                return org.yamcs.protobuf.Alarms.AlarmInfo.Builder.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.Alarms.AlarmInfo.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.Alarms.AlarmInfo.class.getName();
            }
            //unused
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.Alarms.AlarmInfo.Builder builder) throws java.io.IOException {}
        }
        public static java.lang.String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "id";
                case 2: return "type";
                case 3: return "triggerValue";
                case 4: return "mostSevereValue";
                case 5: return "currentValue";
                case 6: return "violations";
                case 7: return "acknowledgeInfo";
                default: return null;
            }
        }
        public static int getFieldNumber(java.lang.String name)
        {
            java.lang.Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }
        private static final java.util.HashMap<java.lang.String,java.lang.Integer> fieldMap = new java.util.HashMap<java.lang.String,java.lang.Integer>();
        static
        {
            fieldMap.put("id", 1);
            fieldMap.put("type", 2);
            fieldMap.put("triggerValue", 3);
            fieldMap.put("mostSevereValue", 4);
            fieldMap.put("currentValue", 5);
            fieldMap.put("violations", 6);
            fieldMap.put("acknowledgeInfo", 7);
        }
    }

}
