// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from yamcsManagement.proto

package org.yamcs.protobuf;


public final class SchemaYamcsManagement
{

    public static final class ProcessorInfo
    {
        public static final org.yamcs.protobuf.SchemaYamcsManagement.ProcessorInfo.MessageSchema WRITE =
            new org.yamcs.protobuf.SchemaYamcsManagement.ProcessorInfo.MessageSchema();
        public static final org.yamcs.protobuf.SchemaYamcsManagement.ProcessorInfo.BuilderSchema MERGE =
            new org.yamcs.protobuf.SchemaYamcsManagement.ProcessorInfo.BuilderSchema();
        
        public static class MessageSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.ProcessorInfo>
        {
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.ProcessorInfo message) throws java.io.IOException
            {
                if(message.hasInstance())
                    output.writeString(1, message.getInstance(), false);
                if(message.hasName())
                    output.writeString(2, message.getName(), false);
                if(message.hasType())
                    output.writeString(3, message.getType(), false);
                if(message.hasSpec())
                    output.writeString(4, message.getSpec(), false);
                if(message.hasCreator())
                    output.writeString(5, message.getCreator(), false);
                if(message.hasHasCommanding())
                    output.writeBool(6, message.getHasCommanding(), false);
                if(message.hasState())
                    output.writeEnum(7, message.getState().getNumber(), false);
                if(message.hasReplayRequest())
                    output.writeObject(8, message.getReplayRequest(), org.yamcs.protobuf.SchemaYamcs.ReplayRequest.WRITE, false);

                if(message.hasReplayState())
                    output.writeEnum(9, message.getReplayState().getNumber(), false);
            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.ProcessorInfo message)
            {
                return message.isInitialized();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ProcessorInfo.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ProcessorInfo.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.ProcessorInfo> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorInfo.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorInfo.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorInfo.class.getName();
            }
            //unused
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.ProcessorInfo message) throws java.io.IOException {}
            public org.yamcs.protobuf.YamcsManagement.ProcessorInfo newMessage() { return null; }
        }
        public static class BuilderSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.ProcessorInfo.Builder>
        {
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.ProcessorInfo.Builder builder) throws java.io.IOException
            {
                for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
                {
                    switch(number)
                    {
                        case 0:
                            return;
                        case 1:
                            builder.setInstance(input.readString());
                            break;
                        case 2:
                            builder.setName(input.readString());
                            break;
                        case 3:
                            builder.setType(input.readString());
                            break;
                        case 4:
                            builder.setSpec(input.readString());
                            break;
                        case 5:
                            builder.setCreator(input.readString());
                            break;
                        case 6:
                            builder.setHasCommanding(input.readBool());
                            break;
                        case 7:
                            builder.setState(org.yamcs.protobuf.YamcsManagement.ServiceState.valueOf(input.readEnum()));
                            break;
                        case 8:
                            builder.setReplayRequest(input.mergeObject(org.yamcs.protobuf.Yamcs.ReplayRequest.newBuilder(), org.yamcs.protobuf.SchemaYamcs.ReplayRequest.MERGE));

                            break;
                        case 9:
                            builder.setReplayState(org.yamcs.protobuf.Yamcs.ReplayStatus.ReplayState.valueOf(input.readEnum()));
                            break;
                        default:
                            input.handleUnknownField(number, this);
                    }
                }
            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.ProcessorInfo.Builder builder)
            {
                return builder.isInitialized();
            }
            public org.yamcs.protobuf.YamcsManagement.ProcessorInfo.Builder newMessage()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorInfo.newBuilder();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ProcessorInfo.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ProcessorInfo.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.ProcessorInfo.Builder> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorInfo.Builder.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorInfo.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorInfo.class.getName();
            }
            //unused
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.ProcessorInfo.Builder builder) throws java.io.IOException {}
        }
        public static java.lang.String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "instance";
                case 2: return "name";
                case 3: return "type";
                case 4: return "spec";
                case 5: return "creator";
                case 6: return "hasCommanding";
                case 7: return "state";
                case 8: return "replayRequest";
                case 9: return "replayState";
                default: return null;
            }
        }
        public static int getFieldNumber(java.lang.String name)
        {
            java.lang.Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }
        private static final java.util.HashMap<java.lang.String,java.lang.Integer> fieldMap = new java.util.HashMap<java.lang.String,java.lang.Integer>();
        static
        {
            fieldMap.put("instance", 1);
            fieldMap.put("name", 2);
            fieldMap.put("type", 3);
            fieldMap.put("spec", 4);
            fieldMap.put("creator", 5);
            fieldMap.put("hasCommanding", 6);
            fieldMap.put("state", 7);
            fieldMap.put("replayRequest", 8);
            fieldMap.put("replayState", 9);
        }
    }

    public static final class ClientInfo
    {
        public static final org.yamcs.protobuf.SchemaYamcsManagement.ClientInfo.MessageSchema WRITE =
            new org.yamcs.protobuf.SchemaYamcsManagement.ClientInfo.MessageSchema();
        public static final org.yamcs.protobuf.SchemaYamcsManagement.ClientInfo.BuilderSchema MERGE =
            new org.yamcs.protobuf.SchemaYamcsManagement.ClientInfo.BuilderSchema();
        
        public static class MessageSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.ClientInfo>
        {
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.ClientInfo message) throws java.io.IOException
            {
                if(message.hasInstance())
                    output.writeString(1, message.getInstance(), false);
                if(message.hasId())
                    output.writeInt32(2, message.getId(), false);
                if(message.hasUsername())
                    output.writeString(3, message.getUsername(), false);
                if(message.hasApplicationName())
                    output.writeString(4, message.getApplicationName(), false);
                if(message.hasProcessorName())
                    output.writeString(5, message.getProcessorName(), false);
                if(message.hasState())
                    output.writeEnum(6, message.getState().getNumber(), false);
                if(message.hasCurrentClient())
                    output.writeBool(7, message.getCurrentClient(), false);
            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.ClientInfo message)
            {
                return message.isInitialized();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ClientInfo.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ClientInfo.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.ClientInfo> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.ClientInfo.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.ClientInfo.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.ClientInfo.class.getName();
            }
            //unused
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.ClientInfo message) throws java.io.IOException {}
            public org.yamcs.protobuf.YamcsManagement.ClientInfo newMessage() { return null; }
        }
        public static class BuilderSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.ClientInfo.Builder>
        {
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.ClientInfo.Builder builder) throws java.io.IOException
            {
                for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
                {
                    switch(number)
                    {
                        case 0:
                            return;
                        case 1:
                            builder.setInstance(input.readString());
                            break;
                        case 2:
                            builder.setId(input.readInt32());
                            break;
                        case 3:
                            builder.setUsername(input.readString());
                            break;
                        case 4:
                            builder.setApplicationName(input.readString());
                            break;
                        case 5:
                            builder.setProcessorName(input.readString());
                            break;
                        case 6:
                            builder.setState(org.yamcs.protobuf.YamcsManagement.ClientInfo.ClientState.valueOf(input.readEnum()));
                            break;
                        case 7:
                            builder.setCurrentClient(input.readBool());
                            break;
                        default:
                            input.handleUnknownField(number, this);
                    }
                }
            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.ClientInfo.Builder builder)
            {
                return builder.isInitialized();
            }
            public org.yamcs.protobuf.YamcsManagement.ClientInfo.Builder newMessage()
            {
                return org.yamcs.protobuf.YamcsManagement.ClientInfo.newBuilder();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ClientInfo.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ClientInfo.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.ClientInfo.Builder> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.ClientInfo.Builder.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.ClientInfo.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.ClientInfo.class.getName();
            }
            //unused
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.ClientInfo.Builder builder) throws java.io.IOException {}
        }
        public static java.lang.String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "instance";
                case 2: return "id";
                case 3: return "username";
                case 4: return "applicationName";
                case 5: return "processorName";
                case 6: return "state";
                case 7: return "currentClient";
                default: return null;
            }
        }
        public static int getFieldNumber(java.lang.String name)
        {
            java.lang.Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }
        private static final java.util.HashMap<java.lang.String,java.lang.Integer> fieldMap = new java.util.HashMap<java.lang.String,java.lang.Integer>();
        static
        {
            fieldMap.put("instance", 1);
            fieldMap.put("id", 2);
            fieldMap.put("username", 3);
            fieldMap.put("applicationName", 4);
            fieldMap.put("processorName", 5);
            fieldMap.put("state", 6);
            fieldMap.put("currentClient", 7);
        }
    }

    public static final class TmStatistics
    {
        public static final org.yamcs.protobuf.SchemaYamcsManagement.TmStatistics.MessageSchema WRITE =
            new org.yamcs.protobuf.SchemaYamcsManagement.TmStatistics.MessageSchema();
        public static final org.yamcs.protobuf.SchemaYamcsManagement.TmStatistics.BuilderSchema MERGE =
            new org.yamcs.protobuf.SchemaYamcsManagement.TmStatistics.BuilderSchema();
        
        public static class MessageSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.TmStatistics>
        {
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.TmStatistics message) throws java.io.IOException
            {
                if(message.hasPacketName())
                    output.writeString(1, message.getPacketName(), false);
                if(message.hasReceivedPackets())
                    output.writeInt64(2, message.getReceivedPackets(), false);
                if(message.hasLastReceived())
                    output.writeInt64(3, message.getLastReceived(), false);
                if(message.hasLastPacketTime())
                    output.writeInt64(4, message.getLastPacketTime(), false);
                if(message.hasSubscribedParameterCount())
                    output.writeInt32(6, message.getSubscribedParameterCount(), false);
                if(message.hasLastPacketTimeUTC())
                    output.writeString(7, message.getLastPacketTimeUTC(), false);
                if(message.hasLastReceivedUTC())
                    output.writeString(8, message.getLastReceivedUTC(), false);
            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.TmStatistics message)
            {
                return message.isInitialized();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.TmStatistics.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.TmStatistics.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.TmStatistics> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.TmStatistics.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.TmStatistics.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.TmStatistics.class.getName();
            }
            //unused
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.TmStatistics message) throws java.io.IOException {}
            public org.yamcs.protobuf.YamcsManagement.TmStatistics newMessage() { return null; }
        }
        public static class BuilderSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.TmStatistics.Builder>
        {
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.TmStatistics.Builder builder) throws java.io.IOException
            {
                for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
                {
                    switch(number)
                    {
                        case 0:
                            return;
                        case 1:
                            builder.setPacketName(input.readString());
                            break;
                        case 2:
                            builder.setReceivedPackets(input.readInt64());
                            break;
                        case 3:
                            builder.setLastReceived(input.readInt64());
                            break;
                        case 4:
                            builder.setLastPacketTime(input.readInt64());
                            break;
                        case 6:
                            builder.setSubscribedParameterCount(input.readInt32());
                            break;
                        case 7:
                            builder.setLastPacketTimeUTC(input.readString());
                            break;
                        case 8:
                            builder.setLastReceivedUTC(input.readString());
                            break;
                        default:
                            input.handleUnknownField(number, this);
                    }
                }
            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.TmStatistics.Builder builder)
            {
                return builder.isInitialized();
            }
            public org.yamcs.protobuf.YamcsManagement.TmStatistics.Builder newMessage()
            {
                return org.yamcs.protobuf.YamcsManagement.TmStatistics.newBuilder();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.TmStatistics.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.TmStatistics.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.TmStatistics.Builder> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.TmStatistics.Builder.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.TmStatistics.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.TmStatistics.class.getName();
            }
            //unused
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.TmStatistics.Builder builder) throws java.io.IOException {}
        }
        public static java.lang.String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "packetName";
                case 2: return "receivedPackets";
                case 3: return "lastReceived";
                case 4: return "lastPacketTime";
                case 6: return "subscribedParameterCount";
                case 7: return "lastPacketTimeUTC";
                case 8: return "lastReceivedUTC";
                default: return null;
            }
        }
        public static int getFieldNumber(java.lang.String name)
        {
            java.lang.Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }
        private static final java.util.HashMap<java.lang.String,java.lang.Integer> fieldMap = new java.util.HashMap<java.lang.String,java.lang.Integer>();
        static
        {
            fieldMap.put("packetName", 1);
            fieldMap.put("receivedPackets", 2);
            fieldMap.put("lastReceived", 3);
            fieldMap.put("lastPacketTime", 4);
            fieldMap.put("subscribedParameterCount", 6);
            fieldMap.put("lastPacketTimeUTC", 7);
            fieldMap.put("lastReceivedUTC", 8);
        }
    }

    public static final class Statistics
    {
        public static final org.yamcs.protobuf.SchemaYamcsManagement.Statistics.MessageSchema WRITE =
            new org.yamcs.protobuf.SchemaYamcsManagement.Statistics.MessageSchema();
        public static final org.yamcs.protobuf.SchemaYamcsManagement.Statistics.BuilderSchema MERGE =
            new org.yamcs.protobuf.SchemaYamcsManagement.Statistics.BuilderSchema();
        
        public static class MessageSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.Statistics>
        {
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.Statistics message) throws java.io.IOException
            {
                if(message.hasInstance())
                    output.writeString(1, message.getInstance(), false);
                if(message.hasYProcessorName())
                    output.writeString(2, message.getYProcessorName(), false);
                for(org.yamcs.protobuf.YamcsManagement.TmStatistics tmstats : message.getTmstatsList())
                    output.writeObject(3, tmstats, org.yamcs.protobuf.SchemaYamcsManagement.TmStatistics.WRITE, true);

                if(message.hasLastUpdated())
                    output.writeInt64(4, message.getLastUpdated(), false);
                if(message.hasLastUpdatedUTC())
                    output.writeString(5, message.getLastUpdatedUTC(), false);
            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.Statistics message)
            {
                return message.isInitialized();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.Statistics.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.Statistics.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.Statistics> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.Statistics.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.Statistics.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.Statistics.class.getName();
            }
            //unused
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.Statistics message) throws java.io.IOException {}
            public org.yamcs.protobuf.YamcsManagement.Statistics newMessage() { return null; }
        }
        public static class BuilderSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.Statistics.Builder>
        {
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.Statistics.Builder builder) throws java.io.IOException
            {
                for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
                {
                    switch(number)
                    {
                        case 0:
                            return;
                        case 1:
                            builder.setInstance(input.readString());
                            break;
                        case 2:
                            builder.setYProcessorName(input.readString());
                            break;
                        case 3:
                            builder.addTmstats(input.mergeObject(org.yamcs.protobuf.YamcsManagement.TmStatistics.newBuilder(), org.yamcs.protobuf.SchemaYamcsManagement.TmStatistics.MERGE));

                            break;
                        case 4:
                            builder.setLastUpdated(input.readInt64());
                            break;
                        case 5:
                            builder.setLastUpdatedUTC(input.readString());
                            break;
                        default:
                            input.handleUnknownField(number, this);
                    }
                }
            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.Statistics.Builder builder)
            {
                return builder.isInitialized();
            }
            public org.yamcs.protobuf.YamcsManagement.Statistics.Builder newMessage()
            {
                return org.yamcs.protobuf.YamcsManagement.Statistics.newBuilder();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.Statistics.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.Statistics.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.Statistics.Builder> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.Statistics.Builder.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.Statistics.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.Statistics.class.getName();
            }
            //unused
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.Statistics.Builder builder) throws java.io.IOException {}
        }
        public static java.lang.String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "instance";
                case 2: return "yProcessorName";
                case 3: return "tmstats";
                case 4: return "lastUpdated";
                case 5: return "lastUpdatedUTC";
                default: return null;
            }
        }
        public static int getFieldNumber(java.lang.String name)
        {
            java.lang.Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }
        private static final java.util.HashMap<java.lang.String,java.lang.Integer> fieldMap = new java.util.HashMap<java.lang.String,java.lang.Integer>();
        static
        {
            fieldMap.put("instance", 1);
            fieldMap.put("yProcessorName", 2);
            fieldMap.put("tmstats", 3);
            fieldMap.put("lastUpdated", 4);
            fieldMap.put("lastUpdatedUTC", 5);
        }
    }

    public static final class ProcessorManagementRequest
    {
        public static final org.yamcs.protobuf.SchemaYamcsManagement.ProcessorManagementRequest.MessageSchema WRITE =
            new org.yamcs.protobuf.SchemaYamcsManagement.ProcessorManagementRequest.MessageSchema();
        public static final org.yamcs.protobuf.SchemaYamcsManagement.ProcessorManagementRequest.BuilderSchema MERGE =
            new org.yamcs.protobuf.SchemaYamcsManagement.ProcessorManagementRequest.BuilderSchema();
        
        public static class MessageSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest>
        {
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest message) throws java.io.IOException
            {
                if(message.hasOperation())
                    output.writeEnum(1, message.getOperation().getNumber(), false);
                if(message.hasInstance())
                    output.writeString(2, message.getInstance(), false);
                if(message.hasName())
                    output.writeString(3, message.getName(), false);
                if(message.hasType())
                    output.writeString(4, message.getType(), false);
                if(message.hasSpec())
                    output.writeString(5, message.getSpec(), false);
                for(int clientId : message.getClientIdList())
                    output.writeInt32(6, clientId, true);
                if(message.hasPersistent())
                    output.writeBool(7, message.getPersistent(), false);
                if(message.hasReplaySpec())
                    output.writeObject(8, message.getReplaySpec(), org.yamcs.protobuf.SchemaYamcs.ReplayRequest.WRITE, false);

            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest message)
            {
                return message.isInitialized();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ProcessorManagementRequest.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ProcessorManagementRequest.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest.class.getName();
            }
            //unused
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest message) throws java.io.IOException {}
            public org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest newMessage() { return null; }
        }
        public static class BuilderSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest.Builder>
        {
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest.Builder builder) throws java.io.IOException
            {
                for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
                {
                    switch(number)
                    {
                        case 0:
                            return;
                        case 1:
                            builder.setOperation(org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest.Operation.valueOf(input.readEnum()));
                            break;
                        case 2:
                            builder.setInstance(input.readString());
                            break;
                        case 3:
                            builder.setName(input.readString());
                            break;
                        case 4:
                            builder.setType(input.readString());
                            break;
                        case 5:
                            builder.setSpec(input.readString());
                            break;
                        case 6:
                            builder.addClientId(input.readInt32());
                            break;
                        case 7:
                            builder.setPersistent(input.readBool());
                            break;
                        case 8:
                            builder.setReplaySpec(input.mergeObject(org.yamcs.protobuf.Yamcs.ReplayRequest.newBuilder(), org.yamcs.protobuf.SchemaYamcs.ReplayRequest.MERGE));

                            break;
                        default:
                            input.handleUnknownField(number, this);
                    }
                }
            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest.Builder builder)
            {
                return builder.isInitialized();
            }
            public org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest.Builder newMessage()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest.newBuilder();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ProcessorManagementRequest.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ProcessorManagementRequest.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest.Builder> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest.Builder.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest.class.getName();
            }
            //unused
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.ProcessorManagementRequest.Builder builder) throws java.io.IOException {}
        }
        public static java.lang.String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "operation";
                case 2: return "instance";
                case 3: return "name";
                case 4: return "type";
                case 5: return "spec";
                case 6: return "clientId";
                case 7: return "persistent";
                case 8: return "replaySpec";
                default: return null;
            }
        }
        public static int getFieldNumber(java.lang.String name)
        {
            java.lang.Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }
        private static final java.util.HashMap<java.lang.String,java.lang.Integer> fieldMap = new java.util.HashMap<java.lang.String,java.lang.Integer>();
        static
        {
            fieldMap.put("operation", 1);
            fieldMap.put("instance", 2);
            fieldMap.put("name", 3);
            fieldMap.put("type", 4);
            fieldMap.put("spec", 5);
            fieldMap.put("clientId", 6);
            fieldMap.put("persistent", 7);
            fieldMap.put("replaySpec", 8);
        }
    }

    public static final class ProcessorRequest
    {
        public static final org.yamcs.protobuf.SchemaYamcsManagement.ProcessorRequest.MessageSchema WRITE =
            new org.yamcs.protobuf.SchemaYamcsManagement.ProcessorRequest.MessageSchema();
        public static final org.yamcs.protobuf.SchemaYamcsManagement.ProcessorRequest.BuilderSchema MERGE =
            new org.yamcs.protobuf.SchemaYamcsManagement.ProcessorRequest.BuilderSchema();
        
        public static class MessageSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.ProcessorRequest>
        {
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.ProcessorRequest message) throws java.io.IOException
            {
                if(message.hasOperation())
                    output.writeEnum(1, message.getOperation().getNumber(), false);
                if(message.hasInstance())
                    output.writeString(2, message.getInstance(), false);
                if(message.hasName())
                    output.writeString(3, message.getName(), false);
                if(message.hasSeekTime())
                    output.writeInt64(4, message.getSeekTime(), false);
                if(message.hasReplaySpeed())
                    output.writeObject(5, message.getReplaySpeed(), org.yamcs.protobuf.SchemaYamcs.ReplaySpeed.WRITE, false);

            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.ProcessorRequest message)
            {
                return message.isInitialized();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ProcessorRequest.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ProcessorRequest.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.ProcessorRequest> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorRequest.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorRequest.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorRequest.class.getName();
            }
            //unused
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.ProcessorRequest message) throws java.io.IOException {}
            public org.yamcs.protobuf.YamcsManagement.ProcessorRequest newMessage() { return null; }
        }
        public static class BuilderSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.ProcessorRequest.Builder>
        {
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.ProcessorRequest.Builder builder) throws java.io.IOException
            {
                for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
                {
                    switch(number)
                    {
                        case 0:
                            return;
                        case 1:
                            builder.setOperation(org.yamcs.protobuf.YamcsManagement.ProcessorRequest.Operation.valueOf(input.readEnum()));
                            break;
                        case 2:
                            builder.setInstance(input.readString());
                            break;
                        case 3:
                            builder.setName(input.readString());
                            break;
                        case 4:
                            builder.setSeekTime(input.readInt64());
                            break;
                        case 5:
                            builder.setReplaySpeed(input.mergeObject(org.yamcs.protobuf.Yamcs.ReplaySpeed.newBuilder(), org.yamcs.protobuf.SchemaYamcs.ReplaySpeed.MERGE));

                            break;
                        default:
                            input.handleUnknownField(number, this);
                    }
                }
            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.ProcessorRequest.Builder builder)
            {
                return builder.isInitialized();
            }
            public org.yamcs.protobuf.YamcsManagement.ProcessorRequest.Builder newMessage()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorRequest.newBuilder();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ProcessorRequest.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ProcessorRequest.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.ProcessorRequest.Builder> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorRequest.Builder.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorRequest.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.ProcessorRequest.class.getName();
            }
            //unused
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.ProcessorRequest.Builder builder) throws java.io.IOException {}
        }
        public static java.lang.String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "operation";
                case 2: return "instance";
                case 3: return "name";
                case 4: return "seekTime";
                case 5: return "replaySpeed";
                default: return null;
            }
        }
        public static int getFieldNumber(java.lang.String name)
        {
            java.lang.Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }
        private static final java.util.HashMap<java.lang.String,java.lang.Integer> fieldMap = new java.util.HashMap<java.lang.String,java.lang.Integer>();
        static
        {
            fieldMap.put("operation", 1);
            fieldMap.put("instance", 2);
            fieldMap.put("name", 3);
            fieldMap.put("seekTime", 4);
            fieldMap.put("replaySpeed", 5);
        }
    }

    public static final class LinkInfo
    {
        public static final org.yamcs.protobuf.SchemaYamcsManagement.LinkInfo.MessageSchema WRITE =
            new org.yamcs.protobuf.SchemaYamcsManagement.LinkInfo.MessageSchema();
        public static final org.yamcs.protobuf.SchemaYamcsManagement.LinkInfo.BuilderSchema MERGE =
            new org.yamcs.protobuf.SchemaYamcsManagement.LinkInfo.BuilderSchema();
        
        public static class MessageSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.LinkInfo>
        {
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.LinkInfo message) throws java.io.IOException
            {
                if(message.hasInstance())
                    output.writeString(1, message.getInstance(), false);
                if(message.hasName())
                    output.writeString(2, message.getName(), false);
                if(message.hasType())
                    output.writeString(3, message.getType(), false);
                if(message.hasSpec())
                    output.writeString(4, message.getSpec(), false);
                if(message.hasStream())
                    output.writeString(5, message.getStream(), false);
                if(message.hasDisabled())
                    output.writeBool(6, message.getDisabled(), false);
                if(message.hasStatus())
                    output.writeString(7, message.getStatus(), false);
                if(message.hasDataCount())
                    output.writeInt64(8, message.getDataCount(), false);
                if(message.hasDetailedStatus())
                    output.writeString(9, message.getDetailedStatus(), false);
            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.LinkInfo message)
            {
                return message.isInitialized();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.LinkInfo.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.LinkInfo.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.LinkInfo> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.LinkInfo.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.LinkInfo.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.LinkInfo.class.getName();
            }
            //unused
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.LinkInfo message) throws java.io.IOException {}
            public org.yamcs.protobuf.YamcsManagement.LinkInfo newMessage() { return null; }
        }
        public static class BuilderSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.LinkInfo.Builder>
        {
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.LinkInfo.Builder builder) throws java.io.IOException
            {
                for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
                {
                    switch(number)
                    {
                        case 0:
                            return;
                        case 1:
                            builder.setInstance(input.readString());
                            break;
                        case 2:
                            builder.setName(input.readString());
                            break;
                        case 3:
                            builder.setType(input.readString());
                            break;
                        case 4:
                            builder.setSpec(input.readString());
                            break;
                        case 5:
                            builder.setStream(input.readString());
                            break;
                        case 6:
                            builder.setDisabled(input.readBool());
                            break;
                        case 7:
                            builder.setStatus(input.readString());
                            break;
                        case 8:
                            builder.setDataCount(input.readInt64());
                            break;
                        case 9:
                            builder.setDetailedStatus(input.readString());
                            break;
                        default:
                            input.handleUnknownField(number, this);
                    }
                }
            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.LinkInfo.Builder builder)
            {
                return builder.isInitialized();
            }
            public org.yamcs.protobuf.YamcsManagement.LinkInfo.Builder newMessage()
            {
                return org.yamcs.protobuf.YamcsManagement.LinkInfo.newBuilder();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.LinkInfo.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.LinkInfo.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.LinkInfo.Builder> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.LinkInfo.Builder.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.LinkInfo.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.LinkInfo.class.getName();
            }
            //unused
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.LinkInfo.Builder builder) throws java.io.IOException {}
        }
        public static java.lang.String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "instance";
                case 2: return "name";
                case 3: return "type";
                case 4: return "spec";
                case 5: return "stream";
                case 6: return "disabled";
                case 7: return "status";
                case 8: return "dataCount";
                case 9: return "detailedStatus";
                default: return null;
            }
        }
        public static int getFieldNumber(java.lang.String name)
        {
            java.lang.Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }
        private static final java.util.HashMap<java.lang.String,java.lang.Integer> fieldMap = new java.util.HashMap<java.lang.String,java.lang.Integer>();
        static
        {
            fieldMap.put("instance", 1);
            fieldMap.put("name", 2);
            fieldMap.put("type", 3);
            fieldMap.put("spec", 4);
            fieldMap.put("stream", 5);
            fieldMap.put("disabled", 6);
            fieldMap.put("status", 7);
            fieldMap.put("dataCount", 8);
            fieldMap.put("detailedStatus", 9);
        }
    }

    public static final class ListClientsResponse
    {
        public static final org.yamcs.protobuf.SchemaYamcsManagement.ListClientsResponse.MessageSchema WRITE =
            new org.yamcs.protobuf.SchemaYamcsManagement.ListClientsResponse.MessageSchema();
        public static final org.yamcs.protobuf.SchemaYamcsManagement.ListClientsResponse.BuilderSchema MERGE =
            new org.yamcs.protobuf.SchemaYamcsManagement.ListClientsResponse.BuilderSchema();
        
        public static class MessageSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.ListClientsResponse>
        {
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.ListClientsResponse message) throws java.io.IOException
            {
                for(org.yamcs.protobuf.YamcsManagement.ClientInfo clientInfo : message.getClientInfoList())
                    output.writeObject(1, clientInfo, org.yamcs.protobuf.SchemaYamcsManagement.ClientInfo.WRITE, true);

            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.ListClientsResponse message)
            {
                return message.isInitialized();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ListClientsResponse.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ListClientsResponse.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.ListClientsResponse> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.ListClientsResponse.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.ListClientsResponse.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.ListClientsResponse.class.getName();
            }
            //unused
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.ListClientsResponse message) throws java.io.IOException {}
            public org.yamcs.protobuf.YamcsManagement.ListClientsResponse newMessage() { return null; }
        }
        public static class BuilderSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.ListClientsResponse.Builder>
        {
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.ListClientsResponse.Builder builder) throws java.io.IOException
            {
                for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
                {
                    switch(number)
                    {
                        case 0:
                            return;
                        case 1:
                            builder.addClientInfo(input.mergeObject(org.yamcs.protobuf.YamcsManagement.ClientInfo.newBuilder(), org.yamcs.protobuf.SchemaYamcsManagement.ClientInfo.MERGE));

                            break;
                        default:
                            input.handleUnknownField(number, this);
                    }
                }
            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.ListClientsResponse.Builder builder)
            {
                return builder.isInitialized();
            }
            public org.yamcs.protobuf.YamcsManagement.ListClientsResponse.Builder newMessage()
            {
                return org.yamcs.protobuf.YamcsManagement.ListClientsResponse.newBuilder();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ListClientsResponse.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ListClientsResponse.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.ListClientsResponse.Builder> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.ListClientsResponse.Builder.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.ListClientsResponse.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.ListClientsResponse.class.getName();
            }
            //unused
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.ListClientsResponse.Builder builder) throws java.io.IOException {}
        }
        public static java.lang.String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "clientInfo";
                default: return null;
            }
        }
        public static int getFieldNumber(java.lang.String name)
        {
            java.lang.Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }
        private static final java.util.HashMap<java.lang.String,java.lang.Integer> fieldMap = new java.util.HashMap<java.lang.String,java.lang.Integer>();
        static
        {
            fieldMap.put("clientInfo", 1);
        }
    }

    public static final class ListProcessorsResponse
    {
        public static final org.yamcs.protobuf.SchemaYamcsManagement.ListProcessorsResponse.MessageSchema WRITE =
            new org.yamcs.protobuf.SchemaYamcsManagement.ListProcessorsResponse.MessageSchema();
        public static final org.yamcs.protobuf.SchemaYamcsManagement.ListProcessorsResponse.BuilderSchema MERGE =
            new org.yamcs.protobuf.SchemaYamcsManagement.ListProcessorsResponse.BuilderSchema();
        
        public static class MessageSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse>
        {
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse message) throws java.io.IOException
            {
                for(org.yamcs.protobuf.YamcsManagement.ProcessorInfo processor : message.getProcessorList())
                    output.writeObject(1, processor, org.yamcs.protobuf.SchemaYamcsManagement.ProcessorInfo.WRITE, true);

            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse message)
            {
                return message.isInitialized();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ListProcessorsResponse.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ListProcessorsResponse.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse.class.getName();
            }
            //unused
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse message) throws java.io.IOException {}
            public org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse newMessage() { return null; }
        }
        public static class BuilderSchema implements io.protostuff.Schema<org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse.Builder>
        {
            public void mergeFrom(io.protostuff.Input input, org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse.Builder builder) throws java.io.IOException
            {
                for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
                {
                    switch(number)
                    {
                        case 0:
                            return;
                        case 1:
                            builder.addProcessor(input.mergeObject(org.yamcs.protobuf.YamcsManagement.ProcessorInfo.newBuilder(), org.yamcs.protobuf.SchemaYamcsManagement.ProcessorInfo.MERGE));

                            break;
                        default:
                            input.handleUnknownField(number, this);
                    }
                }
            }
            public boolean isInitialized(org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse.Builder builder)
            {
                return builder.isInitialized();
            }
            public org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse.Builder newMessage()
            {
                return org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse.newBuilder();
            }
            public java.lang.String getFieldName(int number)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ListProcessorsResponse.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return org.yamcs.protobuf.SchemaYamcsManagement.ListProcessorsResponse.getFieldNumber(name);
            }
            public java.lang.Class<org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse.Builder> typeClass()
            {
                return org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse.Builder.class;
            }
            public java.lang.String messageName()
            {
                return org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse.class.getName();
            }
            //unused
            public void writeTo(io.protostuff.Output output, org.yamcs.protobuf.YamcsManagement.ListProcessorsResponse.Builder builder) throws java.io.IOException {}
        }
        public static java.lang.String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "processor";
                default: return null;
            }
        }
        public static int getFieldNumber(java.lang.String name)
        {
            java.lang.Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }
        private static final java.util.HashMap<java.lang.String,java.lang.Integer> fieldMap = new java.util.HashMap<java.lang.String,java.lang.Integer>();
        static
        {
            fieldMap.put("processor", 1);
        }
    }

}
